package AoC2022.Day5;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.*;

class Day5Test {

    @ParameterizedTest
    @MethodSource
    public void task1(String input, String expected){
        Day5 testObject = new Day5(input);
        String result = testObject.task1();

        assertEquals(expected, result);
    }

    public static Stream<Arguments> task1(){
        return Stream.of(
                Arguments.of("    [D]    \n" +
                        "[N] [C]    \n" +
                        "[Z] [M] [P]\n" +
                        " 1   2   3 \n" +
                        "\n" +
                        "move 1 from 2 to 1\n" +
                        "move 3 from 1 to 3\n" +
                        "move 2 from 2 to 1\n" +
                        "move 1 from 1 to 2","CMZ"),
                Arguments.of("                    [L]     [H] [W]\n" +
                        "                [J] [Z] [J] [Q] [Q]\n" +
                        "[S]             [M] [C] [T] [F] [B]\n" +
                        "[P]     [H]     [B] [D] [G] [B] [P]\n" +
                        "[W]     [L] [D] [D] [J] [W] [T] [C]\n" +
                        "[N] [T] [R] [T] [T] [T] [M] [M] [G]\n" +
                        "[J] [S] [Q] [S] [Z] [W] [P] [G] [D]\n" +
                        "[Z] [G] [V] [V] [Q] [M] [L] [N] [R]\n" +
                        " 1   2   3   4   5   6   7   8   9 \n" +
                        "\n" +
                        "move 1 from 3 to 5\n" +
                        "move 2 from 2 to 8\n" +
                        "move 4 from 1 to 3\n" +
                        "move 2 from 1 to 4\n" +
                        "move 1 from 7 to 1\n" +
                        "move 2 from 9 to 7\n" +
                        "move 4 from 5 to 9\n" +
                        "move 7 from 8 to 9\n" +
                        "move 2 from 5 to 2\n" +
                        "move 1 from 2 to 9\n" +
                        "move 1 from 1 to 8\n" +
                        "move 1 from 2 to 7\n" +
                        "move 3 from 8 to 2\n" +
                        "move 6 from 9 to 7\n" +
                        "move 5 from 4 to 1\n" +
                        "move 7 from 9 to 5\n" +
                        "move 1 from 4 to 5\n" +
                        "move 4 from 1 to 7\n" +
                        "move 1 from 8 to 1\n" +
                        "move 4 from 7 to 9\n" +
                        "move 1 from 5 to 8\n" +
                        "move 9 from 9 to 3\n" +
                        "move 1 from 8 to 9\n" +
                        "move 1 from 1 to 5\n" +
                        "move 4 from 3 to 2\n" +
                        "move 10 from 5 to 3\n" +
                        "move 8 from 2 to 8\n" +
                        "move 7 from 8 to 3\n" +
                        "move 9 from 7 to 5\n" +
                        "move 1 from 9 to 3\n" +
                        "move 3 from 6 to 4\n" +
                        "move 3 from 7 to 6\n" +
                        "move 1 from 8 to 7\n" +
                        "move 1 from 1 to 8\n" +
                        "move 1 from 4 to 7\n" +
                        "move 5 from 7 to 6\n" +
                        "move 14 from 3 to 7\n" +
                        "move 16 from 3 to 9\n" +
                        "move 1 from 8 to 4\n" +
                        "move 2 from 4 to 9\n" +
                        "move 1 from 3 to 7\n" +
                        "move 1 from 6 to 8\n" +
                        "move 15 from 7 to 2\n" +
                        "move 10 from 9 to 7\n" +
                        "move 7 from 2 to 4\n" +
                        "move 1 from 2 to 7\n" +
                        "move 11 from 6 to 7\n" +
                        "move 5 from 5 to 9\n" +
                        "move 15 from 7 to 8\n" +
                        "move 1 from 7 to 2\n" +
                        "move 2 from 9 to 7\n" +
                        "move 4 from 5 to 1\n" +
                        "move 5 from 4 to 9\n" +
                        "move 6 from 2 to 4\n" +
                        "move 2 from 2 to 5\n" +
                        "move 2 from 1 to 4\n" +
                        "move 1 from 1 to 5\n" +
                        "move 3 from 5 to 6\n" +
                        "move 8 from 7 to 9\n" +
                        "move 9 from 4 to 9\n" +
                        "move 1 from 4 to 8\n" +
                        "move 11 from 9 to 7\n" +
                        "move 4 from 6 to 1\n" +
                        "move 17 from 8 to 7\n" +
                        "move 26 from 7 to 1\n" +
                        "move 1 from 4 to 8\n" +
                        "move 24 from 1 to 7\n" +
                        "move 22 from 9 to 3\n" +
                        "move 1 from 8 to 2\n" +
                        "move 6 from 3 to 4\n" +
                        "move 2 from 1 to 2\n" +
                        "move 1 from 7 to 9\n" +
                        "move 16 from 7 to 3\n" +
                        "move 1 from 9 to 5\n" +
                        "move 6 from 4 to 1\n" +
                        "move 1 from 2 to 7\n" +
                        "move 6 from 3 to 2\n" +
                        "move 1 from 5 to 4\n" +
                        "move 6 from 3 to 5\n" +
                        "move 1 from 4 to 1\n" +
                        "move 3 from 1 to 4\n" +
                        "move 4 from 5 to 4\n" +
                        "move 7 from 1 to 7\n" +
                        "move 6 from 4 to 3\n" +
                        "move 1 from 1 to 6\n" +
                        "move 1 from 2 to 5\n" +
                        "move 1 from 1 to 7\n" +
                        "move 15 from 3 to 1\n" +
                        "move 2 from 2 to 7\n" +
                        "move 3 from 5 to 8\n" +
                        "move 9 from 7 to 5\n" +
                        "move 8 from 5 to 7\n" +
                        "move 3 from 8 to 5\n" +
                        "move 1 from 6 to 9\n" +
                        "move 5 from 7 to 8\n" +
                        "move 3 from 2 to 4\n" +
                        "move 2 from 2 to 5\n" +
                        "move 4 from 3 to 7\n" +
                        "move 5 from 8 to 3\n" +
                        "move 1 from 5 to 8\n" +
                        "move 5 from 3 to 1\n" +
                        "move 2 from 5 to 7\n" +
                        "move 1 from 9 to 8\n" +
                        "move 1 from 5 to 8\n" +
                        "move 19 from 1 to 4\n" +
                        "move 19 from 7 to 1\n" +
                        "move 7 from 1 to 4\n" +
                        "move 1 from 7 to 4\n" +
                        "move 3 from 3 to 5\n" +
                        "move 22 from 4 to 5\n" +
                        "move 3 from 8 to 3\n" +
                        "move 7 from 1 to 8\n" +
                        "move 3 from 3 to 5\n" +
                        "move 3 from 3 to 6\n" +
                        "move 3 from 6 to 9\n" +
                        "move 3 from 9 to 1\n" +
                        "move 1 from 3 to 4\n" +
                        "move 2 from 8 to 9\n" +
                        "move 25 from 5 to 6\n" +
                        "move 4 from 1 to 5\n" +
                        "move 5 from 5 to 4\n" +
                        "move 2 from 8 to 2\n" +
                        "move 1 from 9 to 2\n" +
                        "move 3 from 5 to 7\n" +
                        "move 12 from 6 to 8\n" +
                        "move 1 from 7 to 3\n" +
                        "move 7 from 8 to 1\n" +
                        "move 1 from 5 to 7\n" +
                        "move 1 from 3 to 8\n" +
                        "move 2 from 7 to 4\n" +
                        "move 6 from 8 to 5\n" +
                        "move 10 from 6 to 3\n" +
                        "move 2 from 6 to 2\n" +
                        "move 1 from 6 to 3\n" +
                        "move 17 from 4 to 6\n" +
                        "move 3 from 3 to 9\n" +
                        "move 3 from 8 to 4\n" +
                        "move 1 from 7 to 5\n" +
                        "move 1 from 3 to 8\n" +
                        "move 1 from 2 to 5\n" +
                        "move 10 from 1 to 7\n" +
                        "move 3 from 2 to 7\n" +
                        "move 2 from 1 to 8\n" +
                        "move 15 from 6 to 3\n" +
                        "move 7 from 5 to 9\n" +
                        "move 9 from 9 to 5\n" +
                        "move 1 from 9 to 3\n" +
                        "move 2 from 3 to 5\n" +
                        "move 3 from 8 to 6\n" +
                        "move 1 from 9 to 3\n" +
                        "move 11 from 5 to 8\n" +
                        "move 9 from 3 to 8\n" +
                        "move 1 from 5 to 6\n" +
                        "move 9 from 8 to 5\n" +
                        "move 10 from 7 to 5\n" +
                        "move 5 from 5 to 3\n" +
                        "move 4 from 6 to 8\n" +
                        "move 2 from 6 to 8\n" +
                        "move 2 from 5 to 6\n" +
                        "move 1 from 2 to 1\n" +
                        "move 9 from 5 to 3\n" +
                        "move 2 from 7 to 5\n" +
                        "move 3 from 5 to 4\n" +
                        "move 1 from 4 to 1\n" +
                        "move 2 from 4 to 3\n" +
                        "move 1 from 7 to 1\n" +
                        "move 2 from 1 to 7\n" +
                        "move 3 from 4 to 5\n" +
                        "move 2 from 7 to 3\n" +
                        "move 14 from 3 to 9\n" +
                        "move 13 from 3 to 1\n" +
                        "move 8 from 1 to 4\n" +
                        "move 6 from 1 to 2\n" +
                        "move 11 from 8 to 6\n" +
                        "move 4 from 3 to 9\n" +
                        "move 2 from 9 to 2\n" +
                        "move 1 from 5 to 2\n" +
                        "move 6 from 4 to 9\n" +
                        "move 6 from 8 to 9\n" +
                        "move 6 from 9 to 4\n" +
                        "move 2 from 4 to 7\n" +
                        "move 4 from 4 to 6\n" +
                        "move 4 from 2 to 9\n" +
                        "move 2 from 7 to 9\n" +
                        "move 2 from 2 to 1\n" +
                        "move 3 from 5 to 3\n" +
                        "move 2 from 1 to 7\n" +
                        "move 1 from 5 to 2\n" +
                        "move 7 from 9 to 7\n" +
                        "move 2 from 2 to 8\n" +
                        "move 10 from 6 to 5\n" +
                        "move 5 from 5 to 6\n" +
                        "move 9 from 7 to 8\n" +
                        "move 3 from 3 to 9\n" +
                        "move 4 from 5 to 1\n" +
                        "move 10 from 9 to 3\n" +
                        "move 7 from 6 to 2\n" +
                        "move 5 from 3 to 9\n" +
                        "move 3 from 1 to 7\n" +
                        "move 1 from 4 to 7\n" +
                        "move 1 from 4 to 9\n" +
                        "move 1 from 3 to 7\n" +
                        "move 1 from 2 to 1\n" +
                        "move 1 from 5 to 1\n" +
                        "move 1 from 1 to 7\n" +
                        "move 3 from 6 to 3\n" +
                        "move 3 from 3 to 4\n" +
                        "move 6 from 7 to 4\n" +
                        "move 3 from 9 to 8\n" +
                        "move 9 from 8 to 1\n" +
                        "move 3 from 8 to 1\n" +
                        "move 13 from 9 to 5\n" +
                        "move 2 from 2 to 8\n" +
                        "move 4 from 8 to 3\n" +
                        "move 11 from 1 to 2\n" +
                        "move 14 from 2 to 6\n" +
                        "move 6 from 3 to 8\n" +
                        "move 4 from 9 to 7\n" +
                        "move 10 from 5 to 3\n" +
                        "move 2 from 7 to 3\n" +
                        "move 1 from 1 to 8\n" +
                        "move 1 from 1 to 7\n" +
                        "move 1 from 7 to 8\n" +
                        "move 1 from 1 to 4\n" +
                        "move 8 from 4 to 2\n" +
                        "move 2 from 5 to 1\n" +
                        "move 1 from 1 to 9\n" +
                        "move 1 from 7 to 3\n" +
                        "move 1 from 9 to 5\n" +
                        "move 1 from 4 to 2\n" +
                        "move 1 from 4 to 6\n" +
                        "move 1 from 7 to 3\n" +
                        "move 11 from 6 to 9\n" +
                        "move 4 from 2 to 5\n" +
                        "move 4 from 2 to 5\n" +
                        "move 10 from 5 to 6\n" +
                        "move 9 from 9 to 5\n" +
                        "move 1 from 9 to 2\n" +
                        "move 2 from 8 to 4\n" +
                        "move 1 from 9 to 6\n" +
                        "move 5 from 2 to 1\n" +
                        "move 5 from 8 to 6\n" +
                        "move 4 from 1 to 9\n" +
                        "move 1 from 8 to 1\n" +
                        "move 3 from 9 to 4\n" +
                        "move 5 from 5 to 1\n" +
                        "move 1 from 9 to 7\n" +
                        "move 11 from 6 to 3\n" +
                        "move 4 from 4 to 9\n" +
                        "move 9 from 6 to 5\n" +
                        "move 2 from 6 to 5\n" +
                        "move 3 from 9 to 1\n" +
                        "move 1 from 4 to 8\n" +
                        "move 4 from 1 to 3\n" +
                        "move 3 from 5 to 4\n" +
                        "move 2 from 4 to 9\n" +
                        "move 2 from 9 to 4\n" +
                        "move 1 from 9 to 8\n" +
                        "move 6 from 5 to 4\n" +
                        "move 1 from 7 to 8\n" +
                        "move 3 from 5 to 2\n" +
                        "move 3 from 8 to 5\n" +
                        "move 1 from 2 to 1\n" +
                        "move 24 from 3 to 9\n" +
                        "move 2 from 2 to 1\n" +
                        "move 10 from 1 to 7\n" +
                        "move 18 from 9 to 8\n" +
                        "move 5 from 3 to 7\n" +
                        "move 5 from 9 to 5\n" +
                        "move 12 from 7 to 2\n" +
                        "move 1 from 7 to 6\n" +
                        "move 8 from 4 to 7\n" +
                        "move 1 from 4 to 5\n" +
                        "move 12 from 5 to 9\n" +
                        "move 1 from 6 to 9\n" +
                        "move 3 from 2 to 8\n" +
                        "move 5 from 7 to 3\n" +
                        "move 21 from 8 to 7\n" +
                        "move 3 from 3 to 8\n" +
                        "move 11 from 9 to 5\n" +
                        "move 10 from 5 to 6\n" +
                        "move 3 from 7 to 2\n" +
                        "move 3 from 6 to 4\n" +
                        "move 2 from 3 to 1\n" +
                        "move 2 from 3 to 5\n" +
                        "move 1 from 1 to 7\n" +
                        "move 1 from 1 to 4\n" +
                        "move 3 from 4 to 1\n" +
                        "move 1 from 9 to 1\n" +
                        "move 1 from 4 to 3\n" +
                        "move 3 from 5 to 8\n" +
                        "move 1 from 9 to 6\n" +
                        "move 4 from 2 to 3\n" +
                        "move 6 from 8 to 6\n" +
                        "move 1 from 9 to 3\n" +
                        "move 7 from 2 to 4\n" +
                        "move 5 from 4 to 5\n" +
                        "move 1 from 2 to 6\n" +
                        "move 3 from 1 to 9\n" +
                        "move 3 from 9 to 4\n" +
                        "move 1 from 1 to 9\n" +
                        "move 2 from 5 to 3\n" +
                        "move 3 from 5 to 2\n" +
                        "move 4 from 7 to 2\n" +
                        "move 2 from 4 to 3\n" +
                        "move 2 from 2 to 3\n" +
                        "move 2 from 4 to 8\n" +
                        "move 5 from 2 to 3\n" +
                        "move 6 from 6 to 4\n" +
                        "move 8 from 7 to 3\n" +
                        "move 4 from 4 to 5\n" +
                        "move 1 from 3 to 1\n" +
                        "move 2 from 8 to 6\n" +
                        "move 7 from 7 to 5\n" +
                        "move 1 from 9 to 1\n" +
                        "move 14 from 3 to 6\n" +
                        "move 4 from 7 to 1\n" +
                        "move 6 from 5 to 3\n" +
                        "move 4 from 1 to 2\n" +
                        "move 9 from 3 to 5\n" +
                        "move 1 from 7 to 2\n" +
                        "move 2 from 3 to 7\n" +
                        "move 1 from 4 to 8\n" +
                        "move 1 from 4 to 9\n" +
                        "move 3 from 3 to 6\n" +
                        "move 9 from 5 to 2\n" +
                        "move 1 from 8 to 9\n" +
                        "move 1 from 1 to 7\n" +
                        "move 1 from 9 to 3\n" +
                        "move 1 from 4 to 8\n" +
                        "move 1 from 9 to 4\n" +
                        "move 3 from 5 to 1\n" +
                        "move 2 from 1 to 9\n" +
                        "move 1 from 4 to 9\n" +
                        "move 15 from 6 to 9\n" +
                        "move 3 from 3 to 5\n" +
                        "move 2 from 1 to 3\n" +
                        "move 2 from 7 to 4\n" +
                        "move 5 from 6 to 5\n" +
                        "move 6 from 2 to 9\n" +
                        "move 1 from 7 to 2\n" +
                        "move 2 from 4 to 6\n" +
                        "move 2 from 3 to 1\n" +
                        "move 1 from 1 to 6\n" +
                        "move 1 from 8 to 3\n" +
                        "move 1 from 3 to 9\n" +
                        "move 3 from 5 to 1\n" +
                        "move 3 from 6 to 2\n" +
                        "move 6 from 5 to 3\n" +
                        "move 6 from 6 to 8\n" +
                        "move 4 from 1 to 6\n" +
                        "move 12 from 9 to 7\n" +
                        "move 4 from 6 to 8\n" +
                        "move 1 from 5 to 1\n" +
                        "move 2 from 8 to 2\n" +
                        "move 2 from 2 to 1\n" +
                        "move 5 from 3 to 6\n" +
                        "move 3 from 1 to 6\n" +
                        "move 5 from 8 to 6\n" +
                        "move 1 from 3 to 6\n" +
                        "move 5 from 2 to 7\n" +
                        "move 8 from 9 to 4\n" +
                        "move 15 from 7 to 8\n" +
                        "move 5 from 6 to 3\n" +
                        "move 1 from 3 to 8\n" +
                        "move 15 from 8 to 3\n" +
                        "move 7 from 2 to 9\n" +
                        "move 1 from 7 to 4\n" +
                        "move 10 from 9 to 5\n" +
                        "move 4 from 6 to 4\n" +
                        "move 3 from 8 to 6\n" +
                        "move 1 from 8 to 6\n" +
                        "move 1 from 7 to 3\n" +
                        "move 10 from 6 to 9\n" +
                        "move 7 from 3 to 2\n" +
                        "move 10 from 9 to 7\n" +
                        "move 8 from 5 to 7\n" +
                        "move 8 from 3 to 7\n" +
                        "move 1 from 5 to 9\n" +
                        "move 1 from 6 to 8\n" +
                        "move 1 from 5 to 4\n" +
                        "move 1 from 8 to 6\n" +
                        "move 5 from 3 to 8\n" +
                        "move 9 from 4 to 2\n" +
                        "move 1 from 9 to 2\n" +
                        "move 4 from 2 to 3\n" +
                        "move 2 from 2 to 9\n" +
                        "move 2 from 4 to 8\n" +
                        "move 4 from 9 to 1\n" +
                        "move 1 from 4 to 9\n" +
                        "move 1 from 7 to 8\n" +
                        "move 9 from 2 to 1\n" +
                        "move 1 from 2 to 5\n" +
                        "move 1 from 5 to 3\n" +
                        "move 1 from 9 to 3\n" +
                        "move 4 from 3 to 6\n" +
                        "move 4 from 8 to 9\n" +
                        "move 2 from 3 to 6\n" +
                        "move 2 from 6 to 9\n" +
                        "move 1 from 4 to 8\n" +
                        "move 3 from 6 to 3\n" +
                        "move 2 from 6 to 5\n" +
                        "move 1 from 5 to 2\n" +
                        "move 2 from 2 to 1\n" +
                        "move 9 from 7 to 3\n" +
                        "move 7 from 3 to 9\n" +
                        "move 9 from 9 to 8\n" +
                        "move 10 from 7 to 1\n" +
                        "move 3 from 9 to 3\n" +
                        "move 3 from 3 to 1\n" +
                        "move 5 from 8 to 3\n" +
                        "move 1 from 9 to 3\n" +
                        "move 1 from 5 to 6\n" +
                        "move 3 from 8 to 4\n" +
                        "move 1 from 8 to 4\n" +
                        "move 2 from 8 to 2\n" +
                        "move 7 from 3 to 8\n" +
                        "move 4 from 4 to 2\n" +
                        "move 1 from 4 to 6\n" +
                        "move 1 from 8 to 1\n" +
                        "move 5 from 7 to 5\n" +
                        "move 2 from 6 to 7\n" +
                        "move 3 from 8 to 7\n" +
                        "move 2 from 2 to 1\n" +
                        "move 23 from 1 to 6\n" +
                        "move 2 from 3 to 5\n" +
                        "move 1 from 3 to 6\n" +
                        "move 1 from 7 to 2\n" +
                        "move 22 from 6 to 4\n" +
                        "move 5 from 2 to 7\n" +
                        "move 6 from 5 to 3\n" +
                        "move 17 from 4 to 1\n" +
                        "move 5 from 8 to 2\n" +
                        "move 23 from 1 to 7\n" +
                        "move 5 from 3 to 1\n" +
                        "move 15 from 7 to 2\n" +
                        "move 2 from 3 to 4\n" +
                        "move 1 from 8 to 4\n" +
                        "move 5 from 1 to 9\n" +
                        "move 6 from 7 to 1\n" +
                        "move 8 from 4 to 6\n" +
                        "move 4 from 9 to 5\n" +
                        "move 3 from 5 to 7\n" +
                        "move 1 from 9 to 1\n" +
                        "move 7 from 7 to 4\n" +
                        "move 7 from 1 to 5\n" +
                        "move 10 from 2 to 3\n" +
                        "move 4 from 2 to 4\n" +
                        "move 6 from 2 to 8\n" +
                        "move 7 from 6 to 7\n" +
                        "move 7 from 3 to 1\n" +
                        "move 3 from 6 to 2\n" +
                        "move 5 from 8 to 7\n" +
                        "move 7 from 5 to 7\n" +
                        "move 1 from 5 to 6\n" +
                        "move 1 from 6 to 2\n" +
                        "move 2 from 3 to 4\n" +
                        "move 1 from 3 to 7\n" +
                        "move 1 from 2 to 6\n" +
                        "move 3 from 7 to 6\n" +
                        "move 1 from 8 to 3\n" +
                        "move 4 from 4 to 2\n" +
                        "move 2 from 4 to 9\n" +
                        "move 2 from 1 to 7\n" +
                        "move 1 from 4 to 9\n" +
                        "move 1 from 3 to 5\n" +
                        "move 4 from 6 to 1\n" +
                        "move 3 from 4 to 5\n" +
                        "move 2 from 4 to 1\n" +
                        "move 8 from 7 to 1\n" +
                        "move 1 from 4 to 1\n" +
                        "move 6 from 2 to 3\n" +
                        "move 1 from 2 to 4\n" +
                        "move 4 from 3 to 2\n" +
                        "move 1 from 4 to 5\n" +
                        "move 3 from 2 to 5\n" +
                        "move 11 from 7 to 5\n" +
                        "move 2 from 9 to 1\n" +
                        "move 8 from 7 to 4\n" +
                        "move 2 from 3 to 5\n" +
                        "move 1 from 2 to 1\n" +
                        "move 8 from 4 to 1\n" +
                        "move 1 from 9 to 4\n" +
                        "move 7 from 5 to 4\n" +
                        "move 22 from 1 to 5\n" +
                        "move 5 from 4 to 2\n" +
                        "move 6 from 1 to 7\n" +
                        "move 4 from 2 to 7\n" +
                        "move 19 from 5 to 4\n" +
                        "move 1 from 7 to 6\n" +
                        "move 3 from 1 to 6\n" +
                        "move 3 from 7 to 9\n" +
                        "move 1 from 2 to 4\n" +
                        "move 20 from 4 to 6\n" +
                        "move 13 from 5 to 9\n" +
                        "move 2 from 1 to 3\n" +
                        "move 10 from 9 to 8\n" +
                        "move 3 from 9 to 4\n" +
                        "move 1 from 8 to 1\n" +
                        "move 1 from 1 to 8\n" +
                        "move 1 from 3 to 1\n" +
                        "move 2 from 9 to 2", "")
        );
    }

    @ParameterizedTest
    @MethodSource
    public void task2(String input, String expected){
        Day5 testObject = new Day5(input);
        String result = testObject.task2();

        assertEquals(expected, result);
    }

    public static Stream<Arguments> task2(){
        return Stream.of(
                Arguments.of("    [D]    \n" +
                        "[N] [C]    \n" +
                        "[Z] [M] [P]\n" +
                        " 1   2   3 \n" +
                        "\n" +
                        "move 1 from 2 to 1\n" +
                        "move 3 from 1 to 3\n" +
                        "move 2 from 2 to 1\n" +
                        "move 1 from 1 to 2", "MCD"),
                Arguments.of("                    [L]     [H] [W]\n" +
                        "                [J] [Z] [J] [Q] [Q]\n" +
                        "[S]             [M] [C] [T] [F] [B]\n" +
                        "[P]     [H]     [B] [D] [G] [B] [P]\n" +
                        "[W]     [L] [D] [D] [J] [W] [T] [C]\n" +
                        "[N] [T] [R] [T] [T] [T] [M] [M] [G]\n" +
                        "[J] [S] [Q] [S] [Z] [W] [P] [G] [D]\n" +
                        "[Z] [G] [V] [V] [Q] [M] [L] [N] [R]\n" +
                        " 1   2   3   4   5   6   7   8   9 \n" +
                        "\n" +
                        "move 1 from 3 to 5\n" +
                        "move 2 from 2 to 8\n" +
                        "move 4 from 1 to 3\n" +
                        "move 2 from 1 to 4\n" +
                        "move 1 from 7 to 1\n" +
                        "move 2 from 9 to 7\n" +
                        "move 4 from 5 to 9\n" +
                        "move 7 from 8 to 9\n" +
                        "move 2 from 5 to 2\n" +
                        "move 1 from 2 to 9\n" +
                        "move 1 from 1 to 8\n" +
                        "move 1 from 2 to 7\n" +
                        "move 3 from 8 to 2\n" +
                        "move 6 from 9 to 7\n" +
                        "move 5 from 4 to 1\n" +
                        "move 7 from 9 to 5\n" +
                        "move 1 from 4 to 5\n" +
                        "move 4 from 1 to 7\n" +
                        "move 1 from 8 to 1\n" +
                        "move 4 from 7 to 9\n" +
                        "move 1 from 5 to 8\n" +
                        "move 9 from 9 to 3\n" +
                        "move 1 from 8 to 9\n" +
                        "move 1 from 1 to 5\n" +
                        "move 4 from 3 to 2\n" +
                        "move 10 from 5 to 3\n" +
                        "move 8 from 2 to 8\n" +
                        "move 7 from 8 to 3\n" +
                        "move 9 from 7 to 5\n" +
                        "move 1 from 9 to 3\n" +
                        "move 3 from 6 to 4\n" +
                        "move 3 from 7 to 6\n" +
                        "move 1 from 8 to 7\n" +
                        "move 1 from 1 to 8\n" +
                        "move 1 from 4 to 7\n" +
                        "move 5 from 7 to 6\n" +
                        "move 14 from 3 to 7\n" +
                        "move 16 from 3 to 9\n" +
                        "move 1 from 8 to 4\n" +
                        "move 2 from 4 to 9\n" +
                        "move 1 from 3 to 7\n" +
                        "move 1 from 6 to 8\n" +
                        "move 15 from 7 to 2\n" +
                        "move 10 from 9 to 7\n" +
                        "move 7 from 2 to 4\n" +
                        "move 1 from 2 to 7\n" +
                        "move 11 from 6 to 7\n" +
                        "move 5 from 5 to 9\n" +
                        "move 15 from 7 to 8\n" +
                        "move 1 from 7 to 2\n" +
                        "move 2 from 9 to 7\n" +
                        "move 4 from 5 to 1\n" +
                        "move 5 from 4 to 9\n" +
                        "move 6 from 2 to 4\n" +
                        "move 2 from 2 to 5\n" +
                        "move 2 from 1 to 4\n" +
                        "move 1 from 1 to 5\n" +
                        "move 3 from 5 to 6\n" +
                        "move 8 from 7 to 9\n" +
                        "move 9 from 4 to 9\n" +
                        "move 1 from 4 to 8\n" +
                        "move 11 from 9 to 7\n" +
                        "move 4 from 6 to 1\n" +
                        "move 17 from 8 to 7\n" +
                        "move 26 from 7 to 1\n" +
                        "move 1 from 4 to 8\n" +
                        "move 24 from 1 to 7\n" +
                        "move 22 from 9 to 3\n" +
                        "move 1 from 8 to 2\n" +
                        "move 6 from 3 to 4\n" +
                        "move 2 from 1 to 2\n" +
                        "move 1 from 7 to 9\n" +
                        "move 16 from 7 to 3\n" +
                        "move 1 from 9 to 5\n" +
                        "move 6 from 4 to 1\n" +
                        "move 1 from 2 to 7\n" +
                        "move 6 from 3 to 2\n" +
                        "move 1 from 5 to 4\n" +
                        "move 6 from 3 to 5\n" +
                        "move 1 from 4 to 1\n" +
                        "move 3 from 1 to 4\n" +
                        "move 4 from 5 to 4\n" +
                        "move 7 from 1 to 7\n" +
                        "move 6 from 4 to 3\n" +
                        "move 1 from 1 to 6\n" +
                        "move 1 from 2 to 5\n" +
                        "move 1 from 1 to 7\n" +
                        "move 15 from 3 to 1\n" +
                        "move 2 from 2 to 7\n" +
                        "move 3 from 5 to 8\n" +
                        "move 9 from 7 to 5\n" +
                        "move 8 from 5 to 7\n" +
                        "move 3 from 8 to 5\n" +
                        "move 1 from 6 to 9\n" +
                        "move 5 from 7 to 8\n" +
                        "move 3 from 2 to 4\n" +
                        "move 2 from 2 to 5\n" +
                        "move 4 from 3 to 7\n" +
                        "move 5 from 8 to 3\n" +
                        "move 1 from 5 to 8\n" +
                        "move 5 from 3 to 1\n" +
                        "move 2 from 5 to 7\n" +
                        "move 1 from 9 to 8\n" +
                        "move 1 from 5 to 8\n" +
                        "move 19 from 1 to 4\n" +
                        "move 19 from 7 to 1\n" +
                        "move 7 from 1 to 4\n" +
                        "move 1 from 7 to 4\n" +
                        "move 3 from 3 to 5\n" +
                        "move 22 from 4 to 5\n" +
                        "move 3 from 8 to 3\n" +
                        "move 7 from 1 to 8\n" +
                        "move 3 from 3 to 5\n" +
                        "move 3 from 3 to 6\n" +
                        "move 3 from 6 to 9\n" +
                        "move 3 from 9 to 1\n" +
                        "move 1 from 3 to 4\n" +
                        "move 2 from 8 to 9\n" +
                        "move 25 from 5 to 6\n" +
                        "move 4 from 1 to 5\n" +
                        "move 5 from 5 to 4\n" +
                        "move 2 from 8 to 2\n" +
                        "move 1 from 9 to 2\n" +
                        "move 3 from 5 to 7\n" +
                        "move 12 from 6 to 8\n" +
                        "move 1 from 7 to 3\n" +
                        "move 7 from 8 to 1\n" +
                        "move 1 from 5 to 7\n" +
                        "move 1 from 3 to 8\n" +
                        "move 2 from 7 to 4\n" +
                        "move 6 from 8 to 5\n" +
                        "move 10 from 6 to 3\n" +
                        "move 2 from 6 to 2\n" +
                        "move 1 from 6 to 3\n" +
                        "move 17 from 4 to 6\n" +
                        "move 3 from 3 to 9\n" +
                        "move 3 from 8 to 4\n" +
                        "move 1 from 7 to 5\n" +
                        "move 1 from 3 to 8\n" +
                        "move 1 from 2 to 5\n" +
                        "move 10 from 1 to 7\n" +
                        "move 3 from 2 to 7\n" +
                        "move 2 from 1 to 8\n" +
                        "move 15 from 6 to 3\n" +
                        "move 7 from 5 to 9\n" +
                        "move 9 from 9 to 5\n" +
                        "move 1 from 9 to 3\n" +
                        "move 2 from 3 to 5\n" +
                        "move 3 from 8 to 6\n" +
                        "move 1 from 9 to 3\n" +
                        "move 11 from 5 to 8\n" +
                        "move 9 from 3 to 8\n" +
                        "move 1 from 5 to 6\n" +
                        "move 9 from 8 to 5\n" +
                        "move 10 from 7 to 5\n" +
                        "move 5 from 5 to 3\n" +
                        "move 4 from 6 to 8\n" +
                        "move 2 from 6 to 8\n" +
                        "move 2 from 5 to 6\n" +
                        "move 1 from 2 to 1\n" +
                        "move 9 from 5 to 3\n" +
                        "move 2 from 7 to 5\n" +
                        "move 3 from 5 to 4\n" +
                        "move 1 from 4 to 1\n" +
                        "move 2 from 4 to 3\n" +
                        "move 1 from 7 to 1\n" +
                        "move 2 from 1 to 7\n" +
                        "move 3 from 4 to 5\n" +
                        "move 2 from 7 to 3\n" +
                        "move 14 from 3 to 9\n" +
                        "move 13 from 3 to 1\n" +
                        "move 8 from 1 to 4\n" +
                        "move 6 from 1 to 2\n" +
                        "move 11 from 8 to 6\n" +
                        "move 4 from 3 to 9\n" +
                        "move 2 from 9 to 2\n" +
                        "move 1 from 5 to 2\n" +
                        "move 6 from 4 to 9\n" +
                        "move 6 from 8 to 9\n" +
                        "move 6 from 9 to 4\n" +
                        "move 2 from 4 to 7\n" +
                        "move 4 from 4 to 6\n" +
                        "move 4 from 2 to 9\n" +
                        "move 2 from 7 to 9\n" +
                        "move 2 from 2 to 1\n" +
                        "move 3 from 5 to 3\n" +
                        "move 2 from 1 to 7\n" +
                        "move 1 from 5 to 2\n" +
                        "move 7 from 9 to 7\n" +
                        "move 2 from 2 to 8\n" +
                        "move 10 from 6 to 5\n" +
                        "move 5 from 5 to 6\n" +
                        "move 9 from 7 to 8\n" +
                        "move 3 from 3 to 9\n" +
                        "move 4 from 5 to 1\n" +
                        "move 10 from 9 to 3\n" +
                        "move 7 from 6 to 2\n" +
                        "move 5 from 3 to 9\n" +
                        "move 3 from 1 to 7\n" +
                        "move 1 from 4 to 7\n" +
                        "move 1 from 4 to 9\n" +
                        "move 1 from 3 to 7\n" +
                        "move 1 from 2 to 1\n" +
                        "move 1 from 5 to 1\n" +
                        "move 1 from 1 to 7\n" +
                        "move 3 from 6 to 3\n" +
                        "move 3 from 3 to 4\n" +
                        "move 6 from 7 to 4\n" +
                        "move 3 from 9 to 8\n" +
                        "move 9 from 8 to 1\n" +
                        "move 3 from 8 to 1\n" +
                        "move 13 from 9 to 5\n" +
                        "move 2 from 2 to 8\n" +
                        "move 4 from 8 to 3\n" +
                        "move 11 from 1 to 2\n" +
                        "move 14 from 2 to 6\n" +
                        "move 6 from 3 to 8\n" +
                        "move 4 from 9 to 7\n" +
                        "move 10 from 5 to 3\n" +
                        "move 2 from 7 to 3\n" +
                        "move 1 from 1 to 8\n" +
                        "move 1 from 1 to 7\n" +
                        "move 1 from 7 to 8\n" +
                        "move 1 from 1 to 4\n" +
                        "move 8 from 4 to 2\n" +
                        "move 2 from 5 to 1\n" +
                        "move 1 from 1 to 9\n" +
                        "move 1 from 7 to 3\n" +
                        "move 1 from 9 to 5\n" +
                        "move 1 from 4 to 2\n" +
                        "move 1 from 4 to 6\n" +
                        "move 1 from 7 to 3\n" +
                        "move 11 from 6 to 9\n" +
                        "move 4 from 2 to 5\n" +
                        "move 4 from 2 to 5\n" +
                        "move 10 from 5 to 6\n" +
                        "move 9 from 9 to 5\n" +
                        "move 1 from 9 to 2\n" +
                        "move 2 from 8 to 4\n" +
                        "move 1 from 9 to 6\n" +
                        "move 5 from 2 to 1\n" +
                        "move 5 from 8 to 6\n" +
                        "move 4 from 1 to 9\n" +
                        "move 1 from 8 to 1\n" +
                        "move 3 from 9 to 4\n" +
                        "move 5 from 5 to 1\n" +
                        "move 1 from 9 to 7\n" +
                        "move 11 from 6 to 3\n" +
                        "move 4 from 4 to 9\n" +
                        "move 9 from 6 to 5\n" +
                        "move 2 from 6 to 5\n" +
                        "move 3 from 9 to 1\n" +
                        "move 1 from 4 to 8\n" +
                        "move 4 from 1 to 3\n" +
                        "move 3 from 5 to 4\n" +
                        "move 2 from 4 to 9\n" +
                        "move 2 from 9 to 4\n" +
                        "move 1 from 9 to 8\n" +
                        "move 6 from 5 to 4\n" +
                        "move 1 from 7 to 8\n" +
                        "move 3 from 5 to 2\n" +
                        "move 3 from 8 to 5\n" +
                        "move 1 from 2 to 1\n" +
                        "move 24 from 3 to 9\n" +
                        "move 2 from 2 to 1\n" +
                        "move 10 from 1 to 7\n" +
                        "move 18 from 9 to 8\n" +
                        "move 5 from 3 to 7\n" +
                        "move 5 from 9 to 5\n" +
                        "move 12 from 7 to 2\n" +
                        "move 1 from 7 to 6\n" +
                        "move 8 from 4 to 7\n" +
                        "move 1 from 4 to 5\n" +
                        "move 12 from 5 to 9\n" +
                        "move 1 from 6 to 9\n" +
                        "move 3 from 2 to 8\n" +
                        "move 5 from 7 to 3\n" +
                        "move 21 from 8 to 7\n" +
                        "move 3 from 3 to 8\n" +
                        "move 11 from 9 to 5\n" +
                        "move 10 from 5 to 6\n" +
                        "move 3 from 7 to 2\n" +
                        "move 3 from 6 to 4\n" +
                        "move 2 from 3 to 1\n" +
                        "move 2 from 3 to 5\n" +
                        "move 1 from 1 to 7\n" +
                        "move 1 from 1 to 4\n" +
                        "move 3 from 4 to 1\n" +
                        "move 1 from 9 to 1\n" +
                        "move 1 from 4 to 3\n" +
                        "move 3 from 5 to 8\n" +
                        "move 1 from 9 to 6\n" +
                        "move 4 from 2 to 3\n" +
                        "move 6 from 8 to 6\n" +
                        "move 1 from 9 to 3\n" +
                        "move 7 from 2 to 4\n" +
                        "move 5 from 4 to 5\n" +
                        "move 1 from 2 to 6\n" +
                        "move 3 from 1 to 9\n" +
                        "move 3 from 9 to 4\n" +
                        "move 1 from 1 to 9\n" +
                        "move 2 from 5 to 3\n" +
                        "move 3 from 5 to 2\n" +
                        "move 4 from 7 to 2\n" +
                        "move 2 from 4 to 3\n" +
                        "move 2 from 2 to 3\n" +
                        "move 2 from 4 to 8\n" +
                        "move 5 from 2 to 3\n" +
                        "move 6 from 6 to 4\n" +
                        "move 8 from 7 to 3\n" +
                        "move 4 from 4 to 5\n" +
                        "move 1 from 3 to 1\n" +
                        "move 2 from 8 to 6\n" +
                        "move 7 from 7 to 5\n" +
                        "move 1 from 9 to 1\n" +
                        "move 14 from 3 to 6\n" +
                        "move 4 from 7 to 1\n" +
                        "move 6 from 5 to 3\n" +
                        "move 4 from 1 to 2\n" +
                        "move 9 from 3 to 5\n" +
                        "move 1 from 7 to 2\n" +
                        "move 2 from 3 to 7\n" +
                        "move 1 from 4 to 8\n" +
                        "move 1 from 4 to 9\n" +
                        "move 3 from 3 to 6\n" +
                        "move 9 from 5 to 2\n" +
                        "move 1 from 8 to 9\n" +
                        "move 1 from 1 to 7\n" +
                        "move 1 from 9 to 3\n" +
                        "move 1 from 4 to 8\n" +
                        "move 1 from 9 to 4\n" +
                        "move 3 from 5 to 1\n" +
                        "move 2 from 1 to 9\n" +
                        "move 1 from 4 to 9\n" +
                        "move 15 from 6 to 9\n" +
                        "move 3 from 3 to 5\n" +
                        "move 2 from 1 to 3\n" +
                        "move 2 from 7 to 4\n" +
                        "move 5 from 6 to 5\n" +
                        "move 6 from 2 to 9\n" +
                        "move 1 from 7 to 2\n" +
                        "move 2 from 4 to 6\n" +
                        "move 2 from 3 to 1\n" +
                        "move 1 from 1 to 6\n" +
                        "move 1 from 8 to 3\n" +
                        "move 1 from 3 to 9\n" +
                        "move 3 from 5 to 1\n" +
                        "move 3 from 6 to 2\n" +
                        "move 6 from 5 to 3\n" +
                        "move 6 from 6 to 8\n" +
                        "move 4 from 1 to 6\n" +
                        "move 12 from 9 to 7\n" +
                        "move 4 from 6 to 8\n" +
                        "move 1 from 5 to 1\n" +
                        "move 2 from 8 to 2\n" +
                        "move 2 from 2 to 1\n" +
                        "move 5 from 3 to 6\n" +
                        "move 3 from 1 to 6\n" +
                        "move 5 from 8 to 6\n" +
                        "move 1 from 3 to 6\n" +
                        "move 5 from 2 to 7\n" +
                        "move 8 from 9 to 4\n" +
                        "move 15 from 7 to 8\n" +
                        "move 5 from 6 to 3\n" +
                        "move 1 from 3 to 8\n" +
                        "move 15 from 8 to 3\n" +
                        "move 7 from 2 to 9\n" +
                        "move 1 from 7 to 4\n" +
                        "move 10 from 9 to 5\n" +
                        "move 4 from 6 to 4\n" +
                        "move 3 from 8 to 6\n" +
                        "move 1 from 8 to 6\n" +
                        "move 1 from 7 to 3\n" +
                        "move 10 from 6 to 9\n" +
                        "move 7 from 3 to 2\n" +
                        "move 10 from 9 to 7\n" +
                        "move 8 from 5 to 7\n" +
                        "move 8 from 3 to 7\n" +
                        "move 1 from 5 to 9\n" +
                        "move 1 from 6 to 8\n" +
                        "move 1 from 5 to 4\n" +
                        "move 1 from 8 to 6\n" +
                        "move 5 from 3 to 8\n" +
                        "move 9 from 4 to 2\n" +
                        "move 1 from 9 to 2\n" +
                        "move 4 from 2 to 3\n" +
                        "move 2 from 2 to 9\n" +
                        "move 2 from 4 to 8\n" +
                        "move 4 from 9 to 1\n" +
                        "move 1 from 4 to 9\n" +
                        "move 1 from 7 to 8\n" +
                        "move 9 from 2 to 1\n" +
                        "move 1 from 2 to 5\n" +
                        "move 1 from 5 to 3\n" +
                        "move 1 from 9 to 3\n" +
                        "move 4 from 3 to 6\n" +
                        "move 4 from 8 to 9\n" +
                        "move 2 from 3 to 6\n" +
                        "move 2 from 6 to 9\n" +
                        "move 1 from 4 to 8\n" +
                        "move 3 from 6 to 3\n" +
                        "move 2 from 6 to 5\n" +
                        "move 1 from 5 to 2\n" +
                        "move 2 from 2 to 1\n" +
                        "move 9 from 7 to 3\n" +
                        "move 7 from 3 to 9\n" +
                        "move 9 from 9 to 8\n" +
                        "move 10 from 7 to 1\n" +
                        "move 3 from 9 to 3\n" +
                        "move 3 from 3 to 1\n" +
                        "move 5 from 8 to 3\n" +
                        "move 1 from 9 to 3\n" +
                        "move 1 from 5 to 6\n" +
                        "move 3 from 8 to 4\n" +
                        "move 1 from 8 to 4\n" +
                        "move 2 from 8 to 2\n" +
                        "move 7 from 3 to 8\n" +
                        "move 4 from 4 to 2\n" +
                        "move 1 from 4 to 6\n" +
                        "move 1 from 8 to 1\n" +
                        "move 5 from 7 to 5\n" +
                        "move 2 from 6 to 7\n" +
                        "move 3 from 8 to 7\n" +
                        "move 2 from 2 to 1\n" +
                        "move 23 from 1 to 6\n" +
                        "move 2 from 3 to 5\n" +
                        "move 1 from 3 to 6\n" +
                        "move 1 from 7 to 2\n" +
                        "move 22 from 6 to 4\n" +
                        "move 5 from 2 to 7\n" +
                        "move 6 from 5 to 3\n" +
                        "move 17 from 4 to 1\n" +
                        "move 5 from 8 to 2\n" +
                        "move 23 from 1 to 7\n" +
                        "move 5 from 3 to 1\n" +
                        "move 15 from 7 to 2\n" +
                        "move 2 from 3 to 4\n" +
                        "move 1 from 8 to 4\n" +
                        "move 5 from 1 to 9\n" +
                        "move 6 from 7 to 1\n" +
                        "move 8 from 4 to 6\n" +
                        "move 4 from 9 to 5\n" +
                        "move 3 from 5 to 7\n" +
                        "move 1 from 9 to 1\n" +
                        "move 7 from 7 to 4\n" +
                        "move 7 from 1 to 5\n" +
                        "move 10 from 2 to 3\n" +
                        "move 4 from 2 to 4\n" +
                        "move 6 from 2 to 8\n" +
                        "move 7 from 6 to 7\n" +
                        "move 7 from 3 to 1\n" +
                        "move 3 from 6 to 2\n" +
                        "move 5 from 8 to 7\n" +
                        "move 7 from 5 to 7\n" +
                        "move 1 from 5 to 6\n" +
                        "move 1 from 6 to 2\n" +
                        "move 2 from 3 to 4\n" +
                        "move 1 from 3 to 7\n" +
                        "move 1 from 2 to 6\n" +
                        "move 3 from 7 to 6\n" +
                        "move 1 from 8 to 3\n" +
                        "move 4 from 4 to 2\n" +
                        "move 2 from 4 to 9\n" +
                        "move 2 from 1 to 7\n" +
                        "move 1 from 4 to 9\n" +
                        "move 1 from 3 to 5\n" +
                        "move 4 from 6 to 1\n" +
                        "move 3 from 4 to 5\n" +
                        "move 2 from 4 to 1\n" +
                        "move 8 from 7 to 1\n" +
                        "move 1 from 4 to 1\n" +
                        "move 6 from 2 to 3\n" +
                        "move 1 from 2 to 4\n" +
                        "move 4 from 3 to 2\n" +
                        "move 1 from 4 to 5\n" +
                        "move 3 from 2 to 5\n" +
                        "move 11 from 7 to 5\n" +
                        "move 2 from 9 to 1\n" +
                        "move 8 from 7 to 4\n" +
                        "move 2 from 3 to 5\n" +
                        "move 1 from 2 to 1\n" +
                        "move 8 from 4 to 1\n" +
                        "move 1 from 9 to 4\n" +
                        "move 7 from 5 to 4\n" +
                        "move 22 from 1 to 5\n" +
                        "move 5 from 4 to 2\n" +
                        "move 6 from 1 to 7\n" +
                        "move 4 from 2 to 7\n" +
                        "move 19 from 5 to 4\n" +
                        "move 1 from 7 to 6\n" +
                        "move 3 from 1 to 6\n" +
                        "move 3 from 7 to 9\n" +
                        "move 1 from 2 to 4\n" +
                        "move 20 from 4 to 6\n" +
                        "move 13 from 5 to 9\n" +
                        "move 2 from 1 to 3\n" +
                        "move 10 from 9 to 8\n" +
                        "move 3 from 9 to 4\n" +
                        "move 1 from 8 to 1\n" +
                        "move 1 from 1 to 8\n" +
                        "move 1 from 3 to 1\n" +
                        "move 2 from 9 to 2","")
        );
    }
}