package AoC2022.Day3;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;

class Day3Test {

    @ParameterizedTest
    @MethodSource
    public void task1(String input, int expected) {
        Day3 testObject = new Day3(input);
        int result = testObject.solveTask1();

        assertEquals(expected, result);
    }

    public static Stream<Arguments> task1() {
        return Stream.of(
                Arguments.of("vJrwpWtwJgWrhcsFMMfFFhFp\n" +
                        "jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL\n" +
                        "PmmdzqPrVvPwwTWBwg\n" +
                        "wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn\n" +
                        "ttgJtRGJQctTZtZT\n" +
                        "CrZsJsPPZsGzwwsLwLmpwMDw", 157),
                Arguments.of("gfWpjRRQffQGCHHJsGqjsj\n" +
                        "SclzJZZvmmnPbJtVSqqNBqVCBdSCsd\n" +
                        "tlbvZJDZtmtPcJmlPnhMFQWWpMRFTfLDRRTWRp\n" +
                        "HjMPgSWjVrjgbHRRSSMRgjRdpdbGdlcdCvQfcCdlwQJfdf\n" +
                        "LNDnhtNtLNFFZDtFnhzvdldDflvvDCdlJfldpJ\n" +
                        "ZFLFZZmFtFtTNTSPRrVPWWMpRP\n" +
                        "qLBSBLRwmgzqCbzCffDlrfCV\n" +
                        "TFFFHNWFMFFMpHpGHMTHGNhrldWZCsdZsslZlZfrflDVss\n" +
                        "PTMcPGntTThHhTGctnMvSwjjvmmqLBmnjqqgCR\n" +
                        "nClJtMwwntqVVPJcgZqq\n" +
                        "mjpsDcrcSSFFPZqFBWWgVP\n" +
                        "vQcjsvhrvvrmhbmNHMNnlHbNMtCtNM\n" +
                        "bgvvhnTQtjrrrhsDDf\n" +
                        "pLSMltLzLLSjFrSSjrSJHD\n" +
                        "zNWRLBdZPllPQtCvttgCqb\n" +
                        "DRlDrrFTNDNlgzsGTBfcnqhhcnJfcrCSqc\n" +
                        "MMmmdWtdLmvtldHjMmQfPBqSJWnfCCCqcWSSPJ\n" +
                        "vjHMjLmjpLtHptQLmHvwTRgNVVpTzZFZgZRlsVTN\n" +
                        "rzpMpDCGFCFFjRFsRPFRNFPv\n" +
                        "fWclbHCHtSmfvjnmfsvZ\n" +
                        "wTcTlSwwtQtWclBQBLGMLMCLVzVLwJGqLd\n" +
                        "MQSjLNjPPLLSBPjfQhSPHjDVCjDtVVpDHwbwVpbD\n" +
                        "RcmWzsRrzZrmTszWRqWlmRJscbtHwCbndCtcDVddDpdnVnbt\n" +
                        "JTsrGGTqmwTlWmTzJzWmhhPLLGgPFgBffSSPhFFM\n" +
                        "qMMRNZMDDNWLPqfzCgDcGncVDCgG\n" +
                        "wwBFhwhhBgmcVzhghG\n" +
                        "tbJbjjtJvwtdtwjpFtlbvtdTLNSMqNqMMgqNHPlZRTNggL\n" +
                        "qmjMHsZmZSbjbZMjSLFFFFwgsgvFswpwww\n" +
                        "hRJBhmnhhvFFwhcv\n" +
                        "llfWDWzrzBNTRfNBrWzzTmZbGTMjPqMmZPjVbSZGSP\n" +
                        "CRRPLwwcclcGVppQ\n" +
                        "SHFjDjjHDTfSDNTTHfSHjQVGrpmllQQWltVVVZGp\n" +
                        "HFlqzDTfqlzwbgPJLwCP\n" +
                        "WRCNLphpLppSCWVHNfLRzVnQMnBnMddPMQDFQgrhPQFM\n" +
                        "jTjJqvqjvPVJFJFBJF\n" +
                        "qTsZbvGqqZlstsmZVljtwqwSHHNWczHSSRcWNSRHzzNfbW\n" +
                        "glgzDzHjSrVHcVgbrjmNsscNGmNWssGNNtst\n" +
                        "hHPQLHJpwdLpdHfQQtnZmNMwnZGZWwsFZM\n" +
                        "QpdhPJRTJfPphJfhCBlVqVvgvVDBbvVqDbHD\n" +
                        "VtHzjZpjVtHrprgGmjHsGHNdSJFQRcLJqCdQcSqJNpcq\n" +
                        "bBWfTPwhbfDlMnhffRwQJQNdqJcLFQLSdR\n" +
                        "bhBhvfMWTnlDnTBfPSmvmjsjmmGtzHtsHm\n" +
                        "pcRPRPWrSDcJGZSStmwZZS\n" +
                        "VnLfCfTlfVzfnMMBCqVNZJdtjNtJjhJdGNNbwT\n" +
                        "BLvqCCMVsnRQsPQgDcZH\n" +
                        "cQbqqQhDGhlQfQlhQrqGsTNgLgCpRgLTPPPLNbpg\n" +
                        "wtHVddVFwSHznZwwznCpRBdjppNBNTTdCjRR\n" +
                        "ZtWFwWtSmvVnwZDrCMGfQlDDJQmD\n" +
                        "PzPZGCZzrZrlhdjdCqfCsqQdRD\n" +
                        "cbvZLVVFvbbNSNFHSDnsDQdnfqNQDRngsR\n" +
                        "FJHSLSFSScJJbWHFmFVFSZmrrzBmhtBwmzBMPMPzPh\n" +
                        "nlpFcLBgcVcLbssGVBGGrlpGPhJJJJJqPBZPDNMQMJJhJQZZ\n" +
                        "SSTjHzfHwtZSPVQVQMRQ\n" +
                        "TzVHwWfTtzwdVzsbFnGgsbdcGrLc\n" +
                        "FppVBRVZDdLmrDGmmfrQ\n" +
                        "NtNMPNshJCzznLGJSrqRrRrr\n" +
                        "tRssthhPlCWhPzsWtzhzCbVVjwTpVwdZZTpwjbdBbwBc\n" +
                        "TTWblHWScvPCCHTWFzSrqqsNNSmdmqrrpz\n" +
                        "RLRwjjnjZNprzmmZcq\n" +
                        "QQgtQnccQDGjgLDRRcLthQhFBvCbMtMHTWlBFllBbFCMTW\n" +
                        "WnBVNvDnVsNvZWdrWDLVDMbsHpTjpHCSSClsbSCCMH\n" +
                        "GPFtmztzgPhRFtJTdbTwjppSCjpgSl\n" +
                        "hJcfPtQhdtWNVZqNnqNQ\n" +
                        "GLcqZPPsnqQcFsmBBrqRvrddNqrC\n" +
                        "MtHthJwLllwvjRvvtrvBRS\n" +
                        "VHMfDLbpfznszZQG\n" +
                        "WBSdPlQPRfBtGQPfBGPBJgzgjwsJzsszJwCrdwCT\n" +
                        "ZpppVpMVpnVHMVVbZRJrCgwRzTJrwNJw\n" +
                        "MvhmnpLqLmhVmBlftRQBFSlR\n" +
                        "hhQlSJqhtCSnqZJnqShSlNDwRzpvdwRlMBMMdcjRjMpMRc\n" +
                        "frrGmLmWbfFrsmFHmBzBvBcwdJbvpjzbMM\n" +
                        "mmgFrVGLWJLFGsgfhSVtVPqntqnnSStN\n" +
                        "SFJTJTSqswwFQbwf\n" +
                        "cDtcWPclrtPwVsfssQmN\n" +
                        "HDtwWCgWdggdzSGJMSzGMq\n" +
                        "JpqJtWRJMhCMJpMQCWtFrjgHdgdlgllwNjlQjldH\n" +
                        "fBzPZcZvnBmDnZvZBZDmPvglVVVdgHHSwrNRgVgwNPRH\n" +
                        "GbZnZccfvcsZmccsmnnZTRbCCMWFTWJqFCCMJFRT\n" +
                        "vrrFqrFTBTmLmNrLMqMTHddJbHpWnhdWdWbHhJGM\n" +
                        "wBzfwzcQSzWSSshpdWGp\n" +
                        "gwjPPPDQtzQlzQDPqTgLBRmRqZBvqFNR\n" +
                        "bWVptFFsbPcZsGLhsZGmLB\n" +
                        "qnWrnrHdMCDCNqfWmvRRZSSRLdRGZGRG\n" +
                        "nNqqNDfMrMWHDQNHzWfHNDnwzblpzFlbwtFbVVlwVcPJpP\n" +
                        "BHJhlHdJQggvddglJBBhglhQzZHPZpFFPDMzFDDRDFZZDFZD\n" +
                        "rSTfqnCffMfCVfCLNqbzbjWNDbbWDPFpPFbP\n" +
                        "nfnnrSfCTVSwrqSLCGfTGlgQhlvsGMJQJBhhssJhGc\n" +
                        "tBjjDjjqfDjLfJlrLgglvmrlmrcc\n" +
                        "TwNNTVhwwpgvGSNNSssS\n" +
                        "TbwhnvvChhbVRTPPRJBJQQfJttMQQJCQfW\n" +
                        "mWSvSQVgmWQsQvspQJlrlLnJLLpCClhhlp\n" +
                        "bFHRjZdNjjBZzFzhtnCllCcJLrCBll\n" +
                        "HFFNHbdZZLZjfPFjHVQmWDDVsvsmTqVqDf\n" +
                        "JJPllQQClqgBCgdHwHbpjVTwHd\n" +
                        "tmGZtjGjHZpVbfMT\n" +
                        "ShGjNGWmDSNcNRtGmshDRzzCvzQJJRBLrvlrBPJv\n" +
                        "cTpqsTWqVVpsNLfvCDFlMFDVFL\n" +
                        "JnndJPddQgzHlvMJFDhLCG\n" +
                        "BjtntgdRnQgzjdBRQBlpNWrTTlNTSwNpWS\n" +
                        "qHmqLVLjmVqsDBLtmjmbtPwCTwwPzGWRgGwGwMwW\n" +
                        "ZhcCNCSprRTWTwSnWW\n" +
                        "hflhZvvQhppZfcNpvrhpQHjVjLmbVmmVHVCFDvqVFb\n" +
                        "nnNrwDnZrspwDNnZsNSDsNbCmpjvMTPQjLMmPmmQPGBTQP\n" +
                        "FdVtRdRfctBQPmTtTLQB\n" +
                        "qhzWVWJqVHwbhlLSsS\n" +
                        "htWmhDhFztnztDhtBmBtghPRSrpfjVwPdfPwpwnRSVrr\n" +
                        "cbCHvgJGcTqbqcbqqqcqsMsRVrSCwffdRPPpVpwCRSwfjj\n" +
                        "GlgGQqTqbgQzttmBNNFz\n" +
                        "NWQNQgdTgjQNddTZfrCQWRDnnnbqnLqnRcjJlqqvDj\n" +
                        "FtSSmSmJhpllcclDvpln\n" +
                        "JBVVSsSFBVBttShFGSPQfCGNdrMfZZTQTZNNdC\n" +
                        "HgHthMhphcbfbMMfHhsGGDCRRVlcVSScsCRz\n" +
                        "nWvPFqLqPNdjnNLnjdJnPdWjGlssDPSsllVCRzlTCTGlSDzS\n" +
                        "RvddJRJQHwQwpZZb\n" +
                        "gdZwgpjZZQtHTdrWrwdpWRnlhNBRlLbFthNhflhBnL\n" +
                        "CVzDCPGMVqVmGsGGbJCmCDvMcRcqnBFFFnRBBNRBBNqhnFfF\n" +
                        "DsmSGsGPzvMGJvdbgTSTbjbSSdgH\n" +
                        "jBGmbNBQGdBNNDJNQRLLVDsHtDRzHHZZcH\n" +
                        "wCWPFWPCrPhPrplvprhwpCHHtszttqZslRVHLtzVlJZL\n" +
                        "vprMMvMnJCwnnPShNGSTfGSfNmmgdNff\n" +
                        "bPtLbvVWWztbLSVVnbszpzQsrcDDBdpRcDrs\n" +
                        "llZmgCZqgCFgmdRdJcscBdJsmQ\n" +
                        "FZlgfqCFfgZHlqCMCglwCFGWntLLSMRSPGPVttWRtVGL\n" +
                        "vtnDsDtrnrSvrMVmbrrJgPCmBm\n" +
                        "FpQHzFclLVzWHhwHLQLlHLzPmMBQCJTdTmCTmBTJTTmgQg\n" +
                        "pllcVWqlffZqZtZD\n" +
                        "TSSZWpsQmZWcTZSvsTTTppNPzrBPrNBrzQNVFrBBNPqP\n" +
                        "CgjmCbtGgftMmLtLmffzBzJJJNVVMNzNBqJrFN\n" +
                        "gjgjLgtLwgbGjHdhhGdvmlnllnpWnplZvcvwTl\n" +
                        "htLrRFRtbbhlGSLRtbJBJsjBmgMMgJgtmBzz\n" +
                        "pZQWddQQfpZZffcDQZwddQwDMqDDsPgGJJzzjqzgJMBJgmms\n" +
                        "QdcQTdwpGNwfrCRlRVlNLSbb\n" +
                        "wrdvpVBVpMGPPjWjGZJJZT\n" +
                        "tChCSlNfCCHtvHHWPHPZ\n" +
                        "RbRRNvmcqcblfMwwdVBQQqqdpL\n" +
                        "qcctqRcqmcHWzHBdDMZhfwthBnwt\n" +
                        "JFsSNMSgNSNJJMGJBBdjhFDfhwhBrwnZ\n" +
                        "TbgbsSgJMTJllblLCSPlsTCVQmRVVWpQzzqpqzVzHLQzcc\n" +
                        "CVcWbjjSSCSSnpjWpCpprhHZlHtHGzHrZrHGclrl\n" +
                        "gqZqdddLgmgNqvTGGHvvmrrGHT\n" +
                        "FFDgZfZNLMgNfdDqDRnsnjBpbSbnMBBWpQpB\n" +
                        "qwpQFwRnqFFfSBSfFt\n" +
                        "LJJLGLWWtZlbgWHgGshhSdSVzmhHmfVzzC\n" +
                        "lrbrbrNNJgDMLLbblGctvvvDqPcqctTTTcqP\n" +
                        "vnblvbfHvlcHMlHlZbSPLTPLwCMBRRPRRFFR\n" +
                        "tszzBqtzDsWVPRSmzLVmVL\n" +
                        "tsNsDDNgGsqBrgBpgdHQbfhflcHdpZvdbh\n" +
                        "cCpLtpGGLsgsppcpmGGHMtjfHRVhvvVVFRfhjV\n" +
                        "NWnnnNNndQnQZdCdzzRVMHzvhhHWWWjj\n" +
                        "CPJJrnSZpGDJLGTL\n" +
                        "cnJzpcnmnQVFbzTlvTHBlb\n" +
                        "tWCDPjfsDGfZhddhjjdTvFTgFgvbnFHvdHqT\n" +
                        "hjfCjwDDGjPthsfhsnGNrJcQcRmJMLVJrJNMLw\n" +
                        "CPPRrSlRccPcwTHwfdwTHdfl\n" +
                        "mLQLLjhQhhQLZvpzssHDhdTswzzTJD\n" +
                        "gmjbBvQLWmgbQZBCSRnnnSMVCBHnBS\n" +
                        "sWrBJbsVqschzhQzHh\n" +
                        "gtFmztnSlSfdlmnZSdSwcwGRTjcTcwwTcHccRg\n" +
                        "FzFDzMZCdDZtCSrJVBMqWVrqNBqN\n" +
                        "TvWlhhfhZJVgtSSl\n" +
                        "ddBdGGdFmmBbdzqqPDDGGmdDZSgttHtZppSgzZHSgMhtMgtz\n" +
                        "PGqdrbbbdPnrcjjhTRWLLc\n" +
                        "trrmJWcrVwVbcPScdcBdGPHH\n" +
                        "JTQnfjlJTpQFfMLlNJHHGDPdGsSdDjHGDPPH\n" +
                        "ffFfnCTTCfTlplTMvNVzqWvwVzrrhwmWhJbW\n" +
                        "hVtDtgcghzJpmmhlwp\n" +
                        "srsnrqqsPqsBPvnqRBRMPbnwlplpmCStJwmzJPtJzJfwSw\n" +
                        "bbrqjBbvGsjGGBWqMVFFVDNVNjZjgtgFgZ\n" +
                        "mnmhBDHhwWCHsTgRsH\n" +
                        "dcSlFvccMFMMFFggNsTzzvvzWnVW\n" +
                        "llQdllZScFplJPpdcZSqBqjhmtnrwrDGnQGhrq\n" +
                        "ZffVNgfTdmPVltsnnGwgQDnB\n" +
                        "rMCFLMHpzCMFzHpzbrcHFLzBwsDsDDnlDBJrDDBBSJSnBn\n" +
                        "MLMjMzqpCzvwqTmwZdvq\n" +
                        "DDNlWPRqgPRPsRFjJQZbchJZbgQJ\n" +
                        "zzrLLznpLbHnjcBHvVvHvJcZ\n" +
                        "ndmrTzbMMTfzrTfnTLrzdpmsPPPqlqGDNNsPCRDRqRsD\n" +
                        "zzdqTNfTfdfhgQhgqMFSjRDtDRWHqtWlwtqDRS\n" +
                        "ssBCrcmpVGZvVRDdSDRwtmWdDb\n" +
                        "rvGPCZLCVCPVBZFdnfThgNgLJNhf\n" +
                        "bslcrssQwDPbQrrcsbsnQrjMLthPMMRhLRhLRgzmgPhRgM\n" +
                        "DffvDfHGfNFdpfTdMtghLBThzVmBhBtM\n" +
                        "SNvJNJdflDDbcDWJ\n" +
                        "HFlHNpWsTlGWbFsGFTGHFLLNzPPhLVPMzVzMNPhhzP\n" +
                        "jSvZtmrqqpcrCpPVzw\n" +
                        "dddQvqDgDmjdSQQdqZjStpffWGgBRWTGfGsRlWBlHF\n" +
                        "THnTbNrdBnLTHHnTnBrWRTndsccZsLZcDqmLDPcDlQDsmmsZ\n" +
                        "ptwzzhpvGSVdqQlmszqmqPqc\n" +
                        "wGVjSddCBggCHFWN\n" +
                        "LFFbdbhhhvwvfTNdRhhRRvMbHDGjcfcGfDjtDHHcHqGjDqqj\n" +
                        "WlQnVpWSSWWsPsgDqDzHDLHjJcttGP\n" +
                        "rrWsZrgVnWrWSlmSlmSBFFbvTThhBFvvZLBhRw\n" +
                        "BgBdcjThvjFcTggrqvVfzlnnPlrqLt\n" +
                        "JpwJGPsQwpwSssHpPLlzlnNlzLLNNLVtsN\n" +
                        "JPMmWGmWPmHbHpJbWGJmDmwbBTRZMBBdZCRTRjFjhCZCCBTT\n" +
                        "BjbcLFRfBRhnbGjCVVvPllpcPtcDmdlPpvPP\n" +
                        "WrMQqCNgsqWWsTNCMZMWWsWPvJDJDddvlpDtZDpDDDDwvP\n" +
                        "qNMzzSzSQsGLbFCSCnVR\n" +
                        "tTRpHJQpQBZcddhhMhvhJN\n" +
                        "zswljflgMFbwPqmNmSdvShLNfLhm\n" +
                        "qFbsMCVgsqMwRWHCWDDBDWpt\n" +
                        "VSTCCWsJvGpHHCNC\n" +
                        "GrqzZrrZjDljcDDlfjMqgRPfPvQPpBHNvHvBpvNQ\n" +
                        "rljncDcznjMqhlhZDnltrzhTsGWtbVLFTTWGsbdWJdFTmL\n" +
                        "mJPDSJJPZPJNrprSNrDmpZGrhFFhBqjGbGGVbFjhhfqBjBRV\n" +
                        "cgnTQHdMQdTHdhqfggBhVqVfVS\n" +
                        "nQdLLddssSJrmsNvZrPz\n" +
                        "jfjffQzZQQMzZZfZZQFgjDWBCRlCBdTTBGGGRpBCgdhdBG\n" +
                        "LrstWtNsbHLsprRBdlGpCwlh\n" +
                        "HLnntbnscqLvvPNNfMWSSmDMDPjzjDzS\n" +
                        "vhcGwWVvglltcfBn\n" +
                        "BBSLrzSJLzJNJrLfPfPRsmDRmflD\n" +
                        "jMjFZJNMqzrzZzFNFjNQqJzbCpBBvWdpvTCWhpVwdvHVCGbG\n" +
                        "HlrnFmRmtRBQPVBTQHHQ\n" +
                        "psSLJsLpTTdPdLTv\n" +
                        "fCGgTgfSSCtRtFFzql\n" +
                        "pfTpStppcDlWfbpDdzQRsQGJhfffQgJHzN\n" +
                        "ZFZFZmBFwVwBVmLmLsRLRhHNzRLRNNzJ\n" +
                        "FnnjwVPmnqqqjBjrTdblldCTpcPJtbTD\n" +
                        "bdZHdWlrjslMMwGG\n" +
                        "rDDTRBTqSqmJLBJRBTSJpmMsMMjhwvfMhjjfVGsLshhC\n" +
                        "BqQFRPFRQBJgzrcZNHFdZt\n" +
                        "wrDdLlDdPWZPTTrwlZpSsPsHVHsSCHnbzMHM\n" +
                        "JtNFttNCjFvpppnMpJgSVS\n" +
                        "NFFqFcCQCvfrZmGdZdmqrW\n" +
                        "GMNNfJnNddJFJWsv\n" +
                        "HSDwCmmghLmwmmHDpsvdFpMWpppptSbp\n" +
                        "zCzBCgzhwmhzLrPnVrMqZBNfGf\n" +
                        "DrHGtbltbCjjjffPrgsmzmcqsgDczdsmgJ\n" +
                        "VZLwQLZLLVwLBQZnLVphhLQQqsTNmzJdcNTzzmJNqlNBsszz\n" +
                        "wZLhVMplpQVRRlpVGPfjCjMGCrbHGWWb\n" +
                        "BHpFrHHbBNTWWTWNhCPwPLNPjCdjLV\n" +
                        "zJRRzJvZlcZsSMJdzSDjDtfDCtDtjDjjjj\n" +
                        "dcJcszQJJGRJzRllMpGHpFTWmrTmBTbWWB\n" +
                        "qnWWqhDhnjmjCMBlNRrfVfRNCB\n" +
                        "vvBLBtGHJTHBddrNVJrVSVdr\n" +
                        "BZLTHbgvHvTFBgTFFvhmWmmZDPmmZDsnqncs\n" +
                        "WBvmjDbSzTMmHHdpNHNF\n" +
                        "ttlflZRfGtfWVRltGtflCdHnJrNJHNHnJddNMNCnpF\n" +
                        "VVwssWQQfRGZcszBQzDbjSBvSBDP\n" +
                        "lSlQqQVqWWVWfqQWVJSTscdmPPwwTTmjjfpjPp\n" +
                        "FCbzHbvHvtgrtFCvbvbbwdTwmsrwnTTpmdswmwcc\n" +
                        "DtZbHdghztlLMQlWWhVQ\n" +
                        "pqzzFSmdFqbQvlpdDGGrGBWPPBVNQnVttZ\n" +
                        "cgcjwfBMhHCjjLMCrtcnPcsnsPGVnrVs\n" +
                        "JgCChjjjBHhRRLLjjhplzvzpSFJvzzlDbSqm\n" +
                        "mZzVQZMhmrffwfQhWhzmrmpBtRcdbnbcdcMpBbDbncdD\n" +
                        "jsLTSlTWRBSDpnDn\n" +
                        "GLTsGWGFsfmJGZVJZm\n" +
                        "BGWshBGnsFWSLWBLlSSLWRJHnrVPrPcNHCNHctnPPJ\n" +
                        "QmvQCqqMTZqvgmvTjpZCMgMtrVctPptHtrNVrptbJJbrRP\n" +
                        "CzjCZfCwDzShDWdF\n" +
                        "HmQlQHmJnpmptmzt\n" +
                        "MTqMjMPvTvVvhpdztZnSwzwZqS\n" +
                        "CcbLLPTMtCCsjHNHQFLRRFlRNN\n" +
                        "GDFwLLLLSrbdPlFBMFsslFHmZH\n" +
                        "TnJCgthHpVTfZMQZQmzWnZ\n" +
                        "hjvtjtghtqJvVjhTgNhJTvdvdDDRbbccrwPdcGwrHS\n" +
                        "MQQMBPzMGQBPBbDQPMhpnRwsGnRhNrFFpRnF\n" +
                        "vmgHcmCTTlvvvZvTmqcTfmCRdddFnwdRdnVwFpVfpRnwNw\n" +
                        "gvmqJTcHclCQJNzjMLWbLj\n" +
                        "DbqqDDbQFqfNtZSLSq\n" +
                        "RrdjPdmrpWBdmWRdccfLtNttSDMZBfftLMLf\n" +
                        "dCcgmgRrWcgcppjCVVVVFHFnDnbJnb\n" +
                        "fZMFfrtVdZSDVwTgjRMLhwTCLj\n" +
                        "cNzPBNpclllzHbmTNRhqCRTgjC\n" +
                        "nhhWJzhGPlQcGvsvfJtSfZfrtt\n" +
                        "PSzrBWQBBGzBlnSnWtDrqHfNfwVwHcLNjHjwcDNmFH\n" +
                        "hbRhtRCRpRvsRgVVVcNHNNNCwLwc\n" +
                        "ZtRTRvttWWzBPlGZ\n" +
                        "tcLnctNsJrWWNDTN\n" +
                        "pwPPSjHSHHfzvmSvvvFVVGqGVqGmFqrDWgDr\n" +
                        "pPSvfPQMzCQCSbhllLnQDhbtQZ\n" +
                        "DmLffDhpVhjjVwvbwNVFbbNSNH\n" +
                        "JRPBgMPRHBrMHMHqrBMqWJBSQQNbCvndNrdvCNCFwFrQnv\n" +
                        "WcqJcPGMGtWRRBtgZjjspGHTLHGHTppm\n" +
                        "ptJtWJpqRwDZZDVWpbDWqlvvflfMjlfCMjdCCdtslv\n" +
                        "rLwTBGBzBBQTzmwCCjvdvlLllddsMl\n" +
                        "NBwTmrGNgrTrcgPpWgWPDSVVPW\n" +
                        "CdglMnrlSSqDPpcsZb\n" +
                        "ccwmVJtvVvVtNhBpBFPDVpqbbD\n" +
                        "TRGQjJjGTmtrTCgHWLfrcn\n" +
                        "JNNhLwWwWQHNPDmmjHpc\n" +
                        "zMqZCvVCSMVqMSTVvZVGsBnlslpmsmzlPmsHPsPB\n" +
                        "qTVqrgdCCbhfHJQFtg\n" +
                        "wNwCBBCZsfQWfmLCGSmmFRGSSF\n" +
                        "zjnPHPVqMhhZLTcbpbSncp\n" +
                        "lVlhlgzlPZlwtgBddJdfvf\n" +
                        "JWRWRRLWJLnjtjnLzGzznflBvfPvPMqMDqdbzblCzC\n" +
                        "TTScTVbHmTsVFrmcsgcHFlPMMvlvrDPdlrDDqdldvl\n" +
                        "bVpcpchgsFZHbhSmSTsHFFjwtZjnjLttntNjLjNLWtjw\n" +
                        "rffjPJzWzrgPpGWHVNqTtmqFTVRH\n" +
                        "cswhvlLBvSLsCtbFccmqVFNTbb\n" +
                        "wwZSCZSnCLsSDGgDmpGnfmmr\n" +
                        "rTfJTNtjfNljlrWSlzRtNlTqsddwGnsnHHwwhssTsnqw\n" +
                        "VpbpZZbvPLbZbbBhwqMHhsGMnJdVwV\n" +
                        "mgQZJDLBJbbbcbgZClCSfWlrCjRjlDCR\n" +
                        "fSpwcVfzsztcSSWNNMbnMRqTvtTv\n" +
                        "mJFmGDDDhGhBJHCQddllqTvCllqTRRWNnMbT\n" +
                        "FdFDGdDDDhhHdZDjhDmpwSPVZszpwZsVgsPRZs", 0)
        );
    }

    @ParameterizedTest
    @MethodSource
    public void task2(String input, int expected) {
        Day3 testObject = new Day3(input);
        int result = testObject.solveTask2();

        assertEquals(expected, result);
    }

    public static Stream<Arguments> task2() {
        return Stream.of(
                Arguments.of("vJrwpWtwJgWrhcsFMMfFFhFp\n" +
                        "jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL\n" +
                        "PmmdzqPrVvPwwTWBwg\n" +
                        "wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn\n" +
                        "ttgJtRGJQctTZtZT\n" +
                        "CrZsJsPPZsGzwwsLwLmpwMDw", 70),
                Arguments.of("gfWpjRRQffQGCHHJsGqjsj\n" +
                        "SclzJZZvmmnPbJtVSqqNBqVCBdSCsd\n" +
                        "tlbvZJDZtmtPcJmlPnhMFQWWpMRFTfLDRRTWRp\n" +
                        "HjMPgSWjVrjgbHRRSSMRgjRdpdbGdlcdCvQfcCdlwQJfdf\n" +
                        "LNDnhtNtLNFFZDtFnhzvdldDflvvDCdlJfldpJ\n" +
                        "ZFLFZZmFtFtTNTSPRrVPWWMpRP\n" +
                        "qLBSBLRwmgzqCbzCffDlrfCV\n" +
                        "TFFFHNWFMFFMpHpGHMTHGNhrldWZCsdZsslZlZfrflDVss\n" +
                        "PTMcPGntTThHhTGctnMvSwjjvmmqLBmnjqqgCR\n" +
                        "nClJtMwwntqVVPJcgZqq\n" +
                        "mjpsDcrcSSFFPZqFBWWgVP\n" +
                        "vQcjsvhrvvrmhbmNHMNnlHbNMtCtNM\n" +
                        "bgvvhnTQtjrrrhsDDf\n" +
                        "pLSMltLzLLSjFrSSjrSJHD\n" +
                        "zNWRLBdZPllPQtCvttgCqb\n" +
                        "DRlDrrFTNDNlgzsGTBfcnqhhcnJfcrCSqc\n" +
                        "MMmmdWtdLmvtldHjMmQfPBqSJWnfCCCqcWSSPJ\n" +
                        "vjHMjLmjpLtHptQLmHvwTRgNVVpTzZFZgZRlsVTN\n" +
                        "rzpMpDCGFCFFjRFsRPFRNFPv\n" +
                        "fWclbHCHtSmfvjnmfsvZ\n" +
                        "wTcTlSwwtQtWclBQBLGMLMCLVzVLwJGqLd\n" +
                        "MQSjLNjPPLLSBPjfQhSPHjDVCjDtVVpDHwbwVpbD\n" +
                        "RcmWzsRrzZrmTszWRqWlmRJscbtHwCbndCtcDVddDpdnVnbt\n" +
                        "JTsrGGTqmwTlWmTzJzWmhhPLLGgPFgBffSSPhFFM\n" +
                        "qMMRNZMDDNWLPqfzCgDcGncVDCgG\n" +
                        "wwBFhwhhBgmcVzhghG\n" +
                        "tbJbjjtJvwtdtwjpFtlbvtdTLNSMqNqMMgqNHPlZRTNggL\n" +
                        "qmjMHsZmZSbjbZMjSLFFFFwgsgvFswpwww\n" +
                        "hRJBhmnhhvFFwhcv\n" +
                        "llfWDWzrzBNTRfNBrWzzTmZbGTMjPqMmZPjVbSZGSP\n" +
                        "CRRPLwwcclcGVppQ\n" +
                        "SHFjDjjHDTfSDNTTHfSHjQVGrpmllQQWltVVVZGp\n" +
                        "HFlqzDTfqlzwbgPJLwCP\n" +
                        "WRCNLphpLppSCWVHNfLRzVnQMnBnMddPMQDFQgrhPQFM\n" +
                        "jTjJqvqjvPVJFJFBJF\n" +
                        "qTsZbvGqqZlstsmZVljtwqwSHHNWczHSSRcWNSRHzzNfbW\n" +
                        "glgzDzHjSrVHcVgbrjmNsscNGmNWssGNNtst\n" +
                        "hHPQLHJpwdLpdHfQQtnZmNMwnZGZWwsFZM\n" +
                        "QpdhPJRTJfPphJfhCBlVqVvgvVDBbvVqDbHD\n" +
                        "VtHzjZpjVtHrprgGmjHsGHNdSJFQRcLJqCdQcSqJNpcq\n" +
                        "bBWfTPwhbfDlMnhffRwQJQNdqJcLFQLSdR\n" +
                        "bhBhvfMWTnlDnTBfPSmvmjsjmmGtzHtsHm\n" +
                        "pcRPRPWrSDcJGZSStmwZZS\n" +
                        "VnLfCfTlfVzfnMMBCqVNZJdtjNtJjhJdGNNbwT\n" +
                        "BLvqCCMVsnRQsPQgDcZH\n" +
                        "cQbqqQhDGhlQfQlhQrqGsTNgLgCpRgLTPPPLNbpg\n" +
                        "wtHVddVFwSHznZwwznCpRBdjppNBNTTdCjRR\n" +
                        "ZtWFwWtSmvVnwZDrCMGfQlDDJQmD\n" +
                        "PzPZGCZzrZrlhdjdCqfCsqQdRD\n" +
                        "cbvZLVVFvbbNSNFHSDnsDQdnfqNQDRngsR\n" +
                        "FJHSLSFSScJJbWHFmFVFSZmrrzBmhtBwmzBMPMPzPh\n" +
                        "nlpFcLBgcVcLbssGVBGGrlpGPhJJJJJqPBZPDNMQMJJhJQZZ\n" +
                        "SSTjHzfHwtZSPVQVQMRQ\n" +
                        "TzVHwWfTtzwdVzsbFnGgsbdcGrLc\n" +
                        "FppVBRVZDdLmrDGmmfrQ\n" +
                        "NtNMPNshJCzznLGJSrqRrRrr\n" +
                        "tRssthhPlCWhPzsWtzhzCbVVjwTpVwdZZTpwjbdBbwBc\n" +
                        "TTWblHWScvPCCHTWFzSrqqsNNSmdmqrrpz\n" +
                        "RLRwjjnjZNprzmmZcq\n" +
                        "QQgtQnccQDGjgLDRRcLthQhFBvCbMtMHTWlBFllBbFCMTW\n" +
                        "WnBVNvDnVsNvZWdrWDLVDMbsHpTjpHCSSClsbSCCMH\n" +
                        "GPFtmztzgPhRFtJTdbTwjppSCjpgSl\n" +
                        "hJcfPtQhdtWNVZqNnqNQ\n" +
                        "GLcqZPPsnqQcFsmBBrqRvrddNqrC\n" +
                        "MtHthJwLllwvjRvvtrvBRS\n" +
                        "VHMfDLbpfznszZQG\n" +
                        "WBSdPlQPRfBtGQPfBGPBJgzgjwsJzsszJwCrdwCT\n" +
                        "ZpppVpMVpnVHMVVbZRJrCgwRzTJrwNJw\n" +
                        "MvhmnpLqLmhVmBlftRQBFSlR\n" +
                        "hhQlSJqhtCSnqZJnqShSlNDwRzpvdwRlMBMMdcjRjMpMRc\n" +
                        "frrGmLmWbfFrsmFHmBzBvBcwdJbvpjzbMM\n" +
                        "mmgFrVGLWJLFGsgfhSVtVPqntqnnSStN\n" +
                        "SFJTJTSqswwFQbwf\n" +
                        "cDtcWPclrtPwVsfssQmN\n" +
                        "HDtwWCgWdggdzSGJMSzGMq\n" +
                        "JpqJtWRJMhCMJpMQCWtFrjgHdgdlgllwNjlQjldH\n" +
                        "fBzPZcZvnBmDnZvZBZDmPvglVVVdgHHSwrNRgVgwNPRH\n" +
                        "GbZnZccfvcsZmccsmnnZTRbCCMWFTWJqFCCMJFRT\n" +
                        "vrrFqrFTBTmLmNrLMqMTHddJbHpWnhdWdWbHhJGM\n" +
                        "wBzfwzcQSzWSSshpdWGp\n" +
                        "gwjPPPDQtzQlzQDPqTgLBRmRqZBvqFNR\n" +
                        "bWVptFFsbPcZsGLhsZGmLB\n" +
                        "qnWrnrHdMCDCNqfWmvRRZSSRLdRGZGRG\n" +
                        "nNqqNDfMrMWHDQNHzWfHNDnwzblpzFlbwtFbVVlwVcPJpP\n" +
                        "BHJhlHdJQggvddglJBBhglhQzZHPZpFFPDMzFDDRDFZZDFZD\n" +
                        "rSTfqnCffMfCVfCLNqbzbjWNDbbWDPFpPFbP\n" +
                        "nfnnrSfCTVSwrqSLCGfTGlgQhlvsGMJQJBhhssJhGc\n" +
                        "tBjjDjjqfDjLfJlrLgglvmrlmrcc\n" +
                        "TwNNTVhwwpgvGSNNSssS\n" +
                        "TbwhnvvChhbVRTPPRJBJQQfJttMQQJCQfW\n" +
                        "mWSvSQVgmWQsQvspQJlrlLnJLLpCClhhlp\n" +
                        "bFHRjZdNjjBZzFzhtnCllCcJLrCBll\n" +
                        "HFFNHbdZZLZjfPFjHVQmWDDVsvsmTqVqDf\n" +
                        "JJPllQQClqgBCgdHwHbpjVTwHd\n" +
                        "tmGZtjGjHZpVbfMT\n" +
                        "ShGjNGWmDSNcNRtGmshDRzzCvzQJJRBLrvlrBPJv\n" +
                        "cTpqsTWqVVpsNLfvCDFlMFDVFL\n" +
                        "JnndJPddQgzHlvMJFDhLCG\n" +
                        "BjtntgdRnQgzjdBRQBlpNWrTTlNTSwNpWS\n" +
                        "qHmqLVLjmVqsDBLtmjmbtPwCTwwPzGWRgGwGwMwW\n" +
                        "ZhcCNCSprRTWTwSnWW\n" +
                        "hflhZvvQhppZfcNpvrhpQHjVjLmbVmmVHVCFDvqVFb\n" +
                        "nnNrwDnZrspwDNnZsNSDsNbCmpjvMTPQjLMmPmmQPGBTQP\n" +
                        "FdVtRdRfctBQPmTtTLQB\n" +
                        "qhzWVWJqVHwbhlLSsS\n" +
                        "htWmhDhFztnztDhtBmBtghPRSrpfjVwPdfPwpwnRSVrr\n" +
                        "cbCHvgJGcTqbqcbqqqcqsMsRVrSCwffdRPPpVpwCRSwfjj\n" +
                        "GlgGQqTqbgQzttmBNNFz\n" +
                        "NWQNQgdTgjQNddTZfrCQWRDnnnbqnLqnRcjJlqqvDj\n" +
                        "FtSSmSmJhpllcclDvpln\n" +
                        "JBVVSsSFBVBttShFGSPQfCGNdrMfZZTQTZNNdC\n" +
                        "HgHthMhphcbfbMMfHhsGGDCRRVlcVSScsCRz\n" +
                        "nWvPFqLqPNdjnNLnjdJnPdWjGlssDPSsllVCRzlTCTGlSDzS\n" +
                        "RvddJRJQHwQwpZZb\n" +
                        "gdZwgpjZZQtHTdrWrwdpWRnlhNBRlLbFthNhflhBnL\n" +
                        "CVzDCPGMVqVmGsGGbJCmCDvMcRcqnBFFFnRBBNRBBNqhnFfF\n" +
                        "DsmSGsGPzvMGJvdbgTSTbjbSSdgH\n" +
                        "jBGmbNBQGdBNNDJNQRLLVDsHtDRzHHZZcH\n" +
                        "wCWPFWPCrPhPrplvprhwpCHHtszttqZslRVHLtzVlJZL\n" +
                        "vprMMvMnJCwnnPShNGSTfGSfNmmgdNff\n" +
                        "bPtLbvVWWztbLSVVnbszpzQsrcDDBdpRcDrs\n" +
                        "llZmgCZqgCFgmdRdJcscBdJsmQ\n" +
                        "FZlgfqCFfgZHlqCMCglwCFGWntLLSMRSPGPVttWRtVGL\n" +
                        "vtnDsDtrnrSvrMVmbrrJgPCmBm\n" +
                        "FpQHzFclLVzWHhwHLQLlHLzPmMBQCJTdTmCTmBTJTTmgQg\n" +
                        "pllcVWqlffZqZtZD\n" +
                        "TSSZWpsQmZWcTZSvsTTTppNPzrBPrNBrzQNVFrBBNPqP\n" +
                        "CgjmCbtGgftMmLtLmffzBzJJJNVVMNzNBqJrFN\n" +
                        "gjgjLgtLwgbGjHdhhGdvmlnllnpWnplZvcvwTl\n" +
                        "htLrRFRtbbhlGSLRtbJBJsjBmgMMgJgtmBzz\n" +
                        "pZQWddQQfpZZffcDQZwddQwDMqDDsPgGJJzzjqzgJMBJgmms\n" +
                        "QdcQTdwpGNwfrCRlRVlNLSbb\n" +
                        "wrdvpVBVpMGPPjWjGZJJZT\n" +
                        "tChCSlNfCCHtvHHWPHPZ\n" +
                        "RbRRNvmcqcblfMwwdVBQQqqdpL\n" +
                        "qcctqRcqmcHWzHBdDMZhfwthBnwt\n" +
                        "JFsSNMSgNSNJJMGJBBdjhFDfhwhBrwnZ\n" +
                        "TbgbsSgJMTJllblLCSPlsTCVQmRVVWpQzzqpqzVzHLQzcc\n" +
                        "CVcWbjjSSCSSnpjWpCpprhHZlHtHGzHrZrHGclrl\n" +
                        "gqZqdddLgmgNqvTGGHvvmrrGHT\n" +
                        "FFDgZfZNLMgNfdDqDRnsnjBpbSbnMBBWpQpB\n" +
                        "qwpQFwRnqFFfSBSfFt\n" +
                        "LJJLGLWWtZlbgWHgGshhSdSVzmhHmfVzzC\n" +
                        "lrbrbrNNJgDMLLbblGctvvvDqPcqctTTTcqP\n" +
                        "vnblvbfHvlcHMlHlZbSPLTPLwCMBRRPRRFFR\n" +
                        "tszzBqtzDsWVPRSmzLVmVL\n" +
                        "tsNsDDNgGsqBrgBpgdHQbfhflcHdpZvdbh\n" +
                        "cCpLtpGGLsgsppcpmGGHMtjfHRVhvvVVFRfhjV\n" +
                        "NWnnnNNndQnQZdCdzzRVMHzvhhHWWWjj\n" +
                        "CPJJrnSZpGDJLGTL\n" +
                        "cnJzpcnmnQVFbzTlvTHBlb\n" +
                        "tWCDPjfsDGfZhddhjjdTvFTgFgvbnFHvdHqT\n" +
                        "hjfCjwDDGjPthsfhsnGNrJcQcRmJMLVJrJNMLw\n" +
                        "CPPRrSlRccPcwTHwfdwTHdfl\n" +
                        "mLQLLjhQhhQLZvpzssHDhdTswzzTJD\n" +
                        "gmjbBvQLWmgbQZBCSRnnnSMVCBHnBS\n" +
                        "sWrBJbsVqschzhQzHh\n" +
                        "gtFmztnSlSfdlmnZSdSwcwGRTjcTcwwTcHccRg\n" +
                        "FzFDzMZCdDZtCSrJVBMqWVrqNBqN\n" +
                        "TvWlhhfhZJVgtSSl\n" +
                        "ddBdGGdFmmBbdzqqPDDGGmdDZSgttHtZppSgzZHSgMhtMgtz\n" +
                        "PGqdrbbbdPnrcjjhTRWLLc\n" +
                        "trrmJWcrVwVbcPScdcBdGPHH\n" +
                        "JTQnfjlJTpQFfMLlNJHHGDPdGsSdDjHGDPPH\n" +
                        "ffFfnCTTCfTlplTMvNVzqWvwVzrrhwmWhJbW\n" +
                        "hVtDtgcghzJpmmhlwp\n" +
                        "srsnrqqsPqsBPvnqRBRMPbnwlplpmCStJwmzJPtJzJfwSw\n" +
                        "bbrqjBbvGsjGGBWqMVFFVDNVNjZjgtgFgZ\n" +
                        "mnmhBDHhwWCHsTgRsH\n" +
                        "dcSlFvccMFMMFFggNsTzzvvzWnVW\n" +
                        "llQdllZScFplJPpdcZSqBqjhmtnrwrDGnQGhrq\n" +
                        "ZffVNgfTdmPVltsnnGwgQDnB\n" +
                        "rMCFLMHpzCMFzHpzbrcHFLzBwsDsDDnlDBJrDDBBSJSnBn\n" +
                        "MLMjMzqpCzvwqTmwZdvq\n" +
                        "DDNlWPRqgPRPsRFjJQZbchJZbgQJ\n" +
                        "zzrLLznpLbHnjcBHvVvHvJcZ\n" +
                        "ndmrTzbMMTfzrTfnTLrzdpmsPPPqlqGDNNsPCRDRqRsD\n" +
                        "zzdqTNfTfdfhgQhgqMFSjRDtDRWHqtWlwtqDRS\n" +
                        "ssBCrcmpVGZvVRDdSDRwtmWdDb\n" +
                        "rvGPCZLCVCPVBZFdnfThgNgLJNhf\n" +
                        "bslcrssQwDPbQrrcsbsnQrjMLthPMMRhLRhLRgzmgPhRgM\n" +
                        "DffvDfHGfNFdpfTdMtghLBThzVmBhBtM\n" +
                        "SNvJNJdflDDbcDWJ\n" +
                        "HFlHNpWsTlGWbFsGFTGHFLLNzPPhLVPMzVzMNPhhzP\n" +
                        "jSvZtmrqqpcrCpPVzw\n" +
                        "dddQvqDgDmjdSQQdqZjStpffWGgBRWTGfGsRlWBlHF\n" +
                        "THnTbNrdBnLTHHnTnBrWRTndsccZsLZcDqmLDPcDlQDsmmsZ\n" +
                        "ptwzzhpvGSVdqQlmszqmqPqc\n" +
                        "wGVjSddCBggCHFWN\n" +
                        "LFFbdbhhhvwvfTNdRhhRRvMbHDGjcfcGfDjtDHHcHqGjDqqj\n" +
                        "WlQnVpWSSWWsPsgDqDzHDLHjJcttGP\n" +
                        "rrWsZrgVnWrWSlmSlmSBFFbvTThhBFvvZLBhRw\n" +
                        "BgBdcjThvjFcTggrqvVfzlnnPlrqLt\n" +
                        "JpwJGPsQwpwSssHpPLlzlnNlzLLNNLVtsN\n" +
                        "JPMmWGmWPmHbHpJbWGJmDmwbBTRZMBBdZCRTRjFjhCZCCBTT\n" +
                        "BjbcLFRfBRhnbGjCVVvPllpcPtcDmdlPpvPP\n" +
                        "WrMQqCNgsqWWsTNCMZMWWsWPvJDJDddvlpDtZDpDDDDwvP\n" +
                        "qNMzzSzSQsGLbFCSCnVR\n" +
                        "tTRpHJQpQBZcddhhMhvhJN\n" +
                        "zswljflgMFbwPqmNmSdvShLNfLhm\n" +
                        "qFbsMCVgsqMwRWHCWDDBDWpt\n" +
                        "VSTCCWsJvGpHHCNC\n" +
                        "GrqzZrrZjDljcDDlfjMqgRPfPvQPpBHNvHvBpvNQ\n" +
                        "rljncDcznjMqhlhZDnltrzhTsGWtbVLFTTWGsbdWJdFTmL\n" +
                        "mJPDSJJPZPJNrprSNrDmpZGrhFFhBqjGbGGVbFjhhfqBjBRV\n" +
                        "cgnTQHdMQdTHdhqfggBhVqVfVS\n" +
                        "nQdLLddssSJrmsNvZrPz\n" +
                        "jfjffQzZQQMzZZfZZQFgjDWBCRlCBdTTBGGGRpBCgdhdBG\n" +
                        "LrstWtNsbHLsprRBdlGpCwlh\n" +
                        "HLnntbnscqLvvPNNfMWSSmDMDPjzjDzS\n" +
                        "vhcGwWVvglltcfBn\n" +
                        "BBSLrzSJLzJNJrLfPfPRsmDRmflD\n" +
                        "jMjFZJNMqzrzZzFNFjNQqJzbCpBBvWdpvTCWhpVwdvHVCGbG\n" +
                        "HlrnFmRmtRBQPVBTQHHQ\n" +
                        "psSLJsLpTTdPdLTv\n" +
                        "fCGgTgfSSCtRtFFzql\n" +
                        "pfTpStppcDlWfbpDdzQRsQGJhfffQgJHzN\n" +
                        "ZFZFZmBFwVwBVmLmLsRLRhHNzRLRNNzJ\n" +
                        "FnnjwVPmnqqqjBjrTdblldCTpcPJtbTD\n" +
                        "bdZHdWlrjslMMwGG\n" +
                        "rDDTRBTqSqmJLBJRBTSJpmMsMMjhwvfMhjjfVGsLshhC\n" +
                        "BqQFRPFRQBJgzrcZNHFdZt\n" +
                        "wrDdLlDdPWZPTTrwlZpSsPsHVHsSCHnbzMHM\n" +
                        "JtNFttNCjFvpppnMpJgSVS\n" +
                        "NFFqFcCQCvfrZmGdZdmqrW\n" +
                        "GMNNfJnNddJFJWsv\n" +
                        "HSDwCmmghLmwmmHDpsvdFpMWpppptSbp\n" +
                        "zCzBCgzhwmhzLrPnVrMqZBNfGf\n" +
                        "DrHGtbltbCjjjffPrgsmzmcqsgDczdsmgJ\n" +
                        "VZLwQLZLLVwLBQZnLVphhLQQqsTNmzJdcNTzzmJNqlNBsszz\n" +
                        "wZLhVMplpQVRRlpVGPfjCjMGCrbHGWWb\n" +
                        "BHpFrHHbBNTWWTWNhCPwPLNPjCdjLV\n" +
                        "zJRRzJvZlcZsSMJdzSDjDtfDCtDtjDjjjj\n" +
                        "dcJcszQJJGRJzRllMpGHpFTWmrTmBTbWWB\n" +
                        "qnWWqhDhnjmjCMBlNRrfVfRNCB\n" +
                        "vvBLBtGHJTHBddrNVJrVSVdr\n" +
                        "BZLTHbgvHvTFBgTFFvhmWmmZDPmmZDsnqncs\n" +
                        "WBvmjDbSzTMmHHdpNHNF\n" +
                        "ttlflZRfGtfWVRltGtflCdHnJrNJHNHnJddNMNCnpF\n" +
                        "VVwssWQQfRGZcszBQzDbjSBvSBDP\n" +
                        "lSlQqQVqWWVWfqQWVJSTscdmPPwwTTmjjfpjPp\n" +
                        "FCbzHbvHvtgrtFCvbvbbwdTwmsrwnTTpmdswmwcc\n" +
                        "DtZbHdghztlLMQlWWhVQ\n" +
                        "pqzzFSmdFqbQvlpdDGGrGBWPPBVNQnVttZ\n" +
                        "cgcjwfBMhHCjjLMCrtcnPcsnsPGVnrVs\n" +
                        "JgCChjjjBHhRRLLjjhplzvzpSFJvzzlDbSqm\n" +
                        "mZzVQZMhmrffwfQhWhzmrmpBtRcdbnbcdcMpBbDbncdD\n" +
                        "jsLTSlTWRBSDpnDn\n" +
                        "GLTsGWGFsfmJGZVJZm\n" +
                        "BGWshBGnsFWSLWBLlSSLWRJHnrVPrPcNHCNHctnPPJ\n" +
                        "QmvQCqqMTZqvgmvTjpZCMgMtrVctPptHtrNVrptbJJbrRP\n" +
                        "CzjCZfCwDzShDWdF\n" +
                        "HmQlQHmJnpmptmzt\n" +
                        "MTqMjMPvTvVvhpdztZnSwzwZqS\n" +
                        "CcbLLPTMtCCsjHNHQFLRRFlRNN\n" +
                        "GDFwLLLLSrbdPlFBMFsslFHmZH\n" +
                        "TnJCgthHpVTfZMQZQmzWnZ\n" +
                        "hjvtjtghtqJvVjhTgNhJTvdvdDDRbbccrwPdcGwrHS\n" +
                        "MQQMBPzMGQBPBbDQPMhpnRwsGnRhNrFFpRnF\n" +
                        "vmgHcmCTTlvvvZvTmqcTfmCRdddFnwdRdnVwFpVfpRnwNw\n" +
                        "gvmqJTcHclCQJNzjMLWbLj\n" +
                        "DbqqDDbQFqfNtZSLSq\n" +
                        "RrdjPdmrpWBdmWRdccfLtNttSDMZBfftLMLf\n" +
                        "dCcgmgRrWcgcppjCVVVVFHFnDnbJnb\n" +
                        "fZMFfrtVdZSDVwTgjRMLhwTCLj\n" +
                        "cNzPBNpclllzHbmTNRhqCRTgjC\n" +
                        "nhhWJzhGPlQcGvsvfJtSfZfrtt\n" +
                        "PSzrBWQBBGzBlnSnWtDrqHfNfwVwHcLNjHjwcDNmFH\n" +
                        "hbRhtRCRpRvsRgVVVcNHNNNCwLwc\n" +
                        "ZtRTRvttWWzBPlGZ\n" +
                        "tcLnctNsJrWWNDTN\n" +
                        "pwPPSjHSHHfzvmSvvvFVVGqGVqGmFqrDWgDr\n" +
                        "pPSvfPQMzCQCSbhllLnQDhbtQZ\n" +
                        "DmLffDhpVhjjVwvbwNVFbbNSNH\n" +
                        "JRPBgMPRHBrMHMHqrBMqWJBSQQNbCvndNrdvCNCFwFrQnv\n" +
                        "WcqJcPGMGtWRRBtgZjjspGHTLHGHTppm\n" +
                        "ptJtWJpqRwDZZDVWpbDWqlvvflfMjlfCMjdCCdtslv\n" +
                        "rLwTBGBzBBQTzmwCCjvdvlLllddsMl\n" +
                        "NBwTmrGNgrTrcgPpWgWPDSVVPW\n" +
                        "CdglMnrlSSqDPpcsZb\n" +
                        "ccwmVJtvVvVtNhBpBFPDVpqbbD\n" +
                        "TRGQjJjGTmtrTCgHWLfrcn\n" +
                        "JNNhLwWwWQHNPDmmjHpc\n" +
                        "zMqZCvVCSMVqMSTVvZVGsBnlslpmsmzlPmsHPsPB\n" +
                        "qTVqrgdCCbhfHJQFtg\n" +
                        "wNwCBBCZsfQWfmLCGSmmFRGSSF\n" +
                        "zjnPHPVqMhhZLTcbpbSncp\n" +
                        "lVlhlgzlPZlwtgBddJdfvf\n" +
                        "JWRWRRLWJLnjtjnLzGzznflBvfPvPMqMDqdbzblCzC\n" +
                        "TTScTVbHmTsVFrmcsgcHFlPMMvlvrDPdlrDDqdldvl\n" +
                        "bVpcpchgsFZHbhSmSTsHFFjwtZjnjLttntNjLjNLWtjw\n" +
                        "rffjPJzWzrgPpGWHVNqTtmqFTVRH\n" +
                        "cswhvlLBvSLsCtbFccmqVFNTbb\n" +
                        "wwZSCZSnCLsSDGgDmpGnfmmr\n" +
                        "rTfJTNtjfNljlrWSlzRtNlTqsddwGnsnHHwwhssTsnqw\n" +
                        "VpbpZZbvPLbZbbBhwqMHhsGMnJdVwV\n" +
                        "mgQZJDLBJbbbcbgZClCSfWlrCjRjlDCR\n" +
                        "fSpwcVfzsztcSSWNNMbnMRqTvtTv\n" +
                        "mJFmGDDDhGhBJHCQddllqTvCllqTRRWNnMbT\n" +
                        "FdFDGdDDDhhHdZDjhDmpwSPVZszpwZsVgsPRZs", 0)
        );
    }
}