package AoC2021.Day2;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;

class Day2Test {

    @ParameterizedTest
    @MethodSource
    void task1(String input, int expectedResult) {
        Day2 testObject = new Day2(input);
        int result = testObject.task1();

        assertEquals(expectedResult, result);
    }

    static Stream<Arguments> task1() {
        return Stream.of(
                Arguments.of("forward 5\n" +
                        "down 5\n" +
                        "forward 8\n" +
                        "up 3\n" +
                        "down 8\n" +
                        "forward 2", 150),
                Arguments.of("forward 9\n" +
                        "down 8\n" +
                        "down 2\n" +
                        "down 4\n" +
                        "up 8\n" +
                        "forward 8\n" +
                        "down 7\n" +
                        "forward 3\n" +
                        "down 8\n" +
                        "down 9\n" +
                        "forward 7\n" +
                        "down 3\n" +
                        "forward 2\n" +
                        "down 6\n" +
                        "forward 8\n" +
                        "down 3\n" +
                        "down 4\n" +
                        "up 2\n" +
                        "forward 1\n" +
                        "up 7\n" +
                        "forward 7\n" +
                        "forward 4\n" +
                        "forward 4\n" +
                        "down 7\n" +
                        "forward 2\n" +
                        "forward 7\n" +
                        "forward 4\n" +
                        "up 5\n" +
                        "forward 4\n" +
                        "forward 8\n" +
                        "forward 8\n" +
                        "down 5\n" +
                        "forward 2\n" +
                        "forward 8\n" +
                        "forward 8\n" +
                        "up 1\n" +
                        "down 4\n" +
                        "down 3\n" +
                        "down 1\n" +
                        "up 9\n" +
                        "down 3\n" +
                        "forward 9\n" +
                        "down 4\n" +
                        "up 8\n" +
                        "up 3\n" +
                        "down 5\n" +
                        "forward 4\n" +
                        "down 4\n" +
                        "down 6\n" +
                        "down 8\n" +
                        "forward 2\n" +
                        "down 7\n" +
                        "forward 9\n" +
                        "up 7\n" +
                        "down 3\n" +
                        "forward 3\n" +
                        "forward 2\n" +
                        "down 4\n" +
                        "down 4\n" +
                        "forward 2\n" +
                        "forward 5\n" +
                        "forward 9\n" +
                        "down 9\n" +
                        "down 2\n" +
                        "forward 1\n" +
                        "up 4\n" +
                        "forward 9\n" +
                        "forward 9\n" +
                        "up 4\n" +
                        "down 2\n" +
                        "up 1\n" +
                        "up 7\n" +
                        "forward 7\n" +
                        "forward 6\n" +
                        "forward 1\n" +
                        "forward 8\n" +
                        "forward 2\n" +
                        "forward 4\n" +
                        "up 4\n" +
                        "down 5\n" +
                        "up 8\n" +
                        "down 4\n" +
                        "forward 4\n" +
                        "forward 2\n" +
                        "forward 2\n" +
                        "down 4\n" +
                        "up 3\n" +
                        "down 7\n" +
                        "down 5\n" +
                        "forward 7\n" +
                        "forward 9\n" +
                        "down 8\n" +
                        "up 1\n" +
                        "forward 5\n" +
                        "up 9\n" +
                        "down 1\n" +
                        "up 5\n" +
                        "down 4\n" +
                        "down 2\n" +
                        "down 5\n" +
                        "down 7\n" +
                        "down 3\n" +
                        "down 9\n" +
                        "forward 8\n" +
                        "up 3\n" +
                        "forward 4\n" +
                        "down 6\n" +
                        "down 4\n" +
                        "up 5\n" +
                        "down 3\n" +
                        "up 4\n" +
                        "forward 8\n" +
                        "forward 2\n" +
                        "down 1\n" +
                        "down 6\n" +
                        "down 9\n" +
                        "down 8\n" +
                        "forward 2\n" +
                        "down 6\n" +
                        "down 2\n" +
                        "up 7\n" +
                        "down 6\n" +
                        "down 4\n" +
                        "up 2\n" +
                        "forward 7\n" +
                        "down 4\n" +
                        "forward 4\n" +
                        "up 8\n" +
                        "down 1\n" +
                        "down 6\n" +
                        "forward 6\n" +
                        "down 5\n" +
                        "down 7\n" +
                        "up 9\n" +
                        "forward 2\n" +
                        "up 1\n" +
                        "down 1\n" +
                        "up 8\n" +
                        "forward 6\n" +
                        "forward 7\n" +
                        "up 1\n" +
                        "down 5\n" +
                        "down 3\n" +
                        "up 9\n" +
                        "down 2\n" +
                        "forward 5\n" +
                        "forward 1\n" +
                        "up 6\n" +
                        "up 4\n" +
                        "forward 6\n" +
                        "down 8\n" +
                        "forward 7\n" +
                        "forward 9\n" +
                        "forward 2\n" +
                        "forward 3\n" +
                        "forward 9\n" +
                        "forward 4\n" +
                        "down 9\n" +
                        "down 4\n" +
                        "forward 9\n" +
                        "forward 4\n" +
                        "forward 9\n" +
                        "forward 2\n" +
                        "forward 1\n" +
                        "down 3\n" +
                        "forward 5\n" +
                        "forward 2\n" +
                        "forward 7\n" +
                        "down 7\n" +
                        "down 4\n" +
                        "up 7\n" +
                        "forward 3\n" +
                        "forward 8\n" +
                        "forward 4\n" +
                        "down 4\n" +
                        "forward 9\n" +
                        "forward 2\n" +
                        "forward 9\n" +
                        "down 5\n" +
                        "forward 2\n" +
                        "down 5\n" +
                        "forward 2\n" +
                        "down 8\n" +
                        "up 8\n" +
                        "down 7\n" +
                        "forward 2\n" +
                        "forward 5\n" +
                        "down 5\n" +
                        "forward 8\n" +
                        "up 9\n" +
                        "forward 7\n" +
                        "forward 5\n" +
                        "forward 3\n" +
                        "down 4\n" +
                        "down 2\n" +
                        "forward 4\n" +
                        "down 4\n" +
                        "forward 6\n" +
                        "down 4\n" +
                        "forward 6\n" +
                        "forward 2\n" +
                        "down 9\n" +
                        "forward 7\n" +
                        "down 5\n" +
                        "up 5\n" +
                        "down 9\n" +
                        "down 5\n" +
                        "down 3\n" +
                        "up 4\n" +
                        "down 6\n" +
                        "down 2\n" +
                        "forward 5\n" +
                        "down 4\n" +
                        "down 1\n" +
                        "down 1\n" +
                        "up 7\n" +
                        "forward 9\n" +
                        "forward 6\n" +
                        "down 2\n" +
                        "down 8\n" +
                        "up 7\n" +
                        "up 2\n" +
                        "forward 9\n" +
                        "down 8\n" +
                        "up 6\n" +
                        "down 8\n" +
                        "down 6\n" +
                        "down 2\n" +
                        "down 9\n" +
                        "forward 5\n" +
                        "down 1\n" +
                        "forward 6\n" +
                        "forward 2\n" +
                        "forward 4\n" +
                        "down 7\n" +
                        "down 4\n" +
                        "down 8\n" +
                        "forward 8\n" +
                        "up 5\n" +
                        "up 8\n" +
                        "up 2\n" +
                        "up 2\n" +
                        "up 2\n" +
                        "down 5\n" +
                        "forward 6\n" +
                        "down 8\n" +
                        "down 2\n" +
                        "up 5\n" +
                        "up 2\n" +
                        "forward 7\n" +
                        "forward 4\n" +
                        "up 9\n" +
                        "forward 7\n" +
                        "up 7\n" +
                        "down 9\n" +
                        "forward 8\n" +
                        "down 5\n" +
                        "forward 4\n" +
                        "down 6\n" +
                        "forward 5\n" +
                        "up 2\n" +
                        "down 9\n" +
                        "down 3\n" +
                        "down 2\n" +
                        "down 3\n" +
                        "forward 2\n" +
                        "forward 4\n" +
                        "forward 9\n" +
                        "up 6\n" +
                        "forward 8\n" +
                        "down 9\n" +
                        "forward 1\n" +
                        "forward 1\n" +
                        "forward 1\n" +
                        "forward 4\n" +
                        "forward 3\n" +
                        "up 5\n" +
                        "forward 2\n" +
                        "down 8\n" +
                        "forward 6\n" +
                        "down 3\n" +
                        "down 9\n" +
                        "up 6\n" +
                        "forward 7\n" +
                        "up 3\n" +
                        "down 1\n" +
                        "forward 1\n" +
                        "forward 1\n" +
                        "forward 2\n" +
                        "forward 5\n" +
                        "down 9\n" +
                        "forward 1\n" +
                        "forward 1\n" +
                        "down 2\n" +
                        "forward 2\n" +
                        "forward 4\n" +
                        "up 8\n" +
                        "down 7\n" +
                        "forward 1\n" +
                        "up 3\n" +
                        "forward 7\n" +
                        "down 6\n" +
                        "forward 5\n" +
                        "up 4\n" +
                        "up 5\n" +
                        "forward 4\n" +
                        "down 7\n" +
                        "down 7\n" +
                        "down 9\n" +
                        "down 3\n" +
                        "down 1\n" +
                        "down 1\n" +
                        "down 9\n" +
                        "down 7\n" +
                        "forward 4\n" +
                        "up 3\n" +
                        "down 8\n" +
                        "down 3\n" +
                        "forward 7\n" +
                        "down 1\n" +
                        "down 8\n" +
                        "forward 5\n" +
                        "down 5\n" +
                        "down 1\n" +
                        "forward 5\n" +
                        "forward 6\n" +
                        "down 3\n" +
                        "down 8\n" +
                        "down 1\n" +
                        "forward 4\n" +
                        "up 5\n" +
                        "forward 5\n" +
                        "down 2\n" +
                        "down 2\n" +
                        "forward 5\n" +
                        "down 5\n" +
                        "forward 5\n" +
                        "forward 1\n" +
                        "down 2\n" +
                        "down 3\n" +
                        "down 3\n" +
                        "down 9\n" +
                        "down 6\n" +
                        "forward 6\n" +
                        "forward 9\n" +
                        "forward 9\n" +
                        "forward 6\n" +
                        "up 2\n" +
                        "up 4\n" +
                        "forward 7\n" +
                        "up 4\n" +
                        "down 4\n" +
                        "forward 4\n" +
                        "down 4\n" +
                        "up 2\n" +
                        "forward 5\n" +
                        "up 9\n" +
                        "down 8\n" +
                        "down 8\n" +
                        "down 1\n" +
                        "down 9\n" +
                        "forward 9\n" +
                        "down 4\n" +
                        "up 2\n" +
                        "up 3\n" +
                        "down 2\n" +
                        "forward 6\n" +
                        "up 4\n" +
                        "up 7\n" +
                        "down 3\n" +
                        "up 2\n" +
                        "forward 6\n" +
                        "down 7\n" +
                        "down 3\n" +
                        "down 6\n" +
                        "down 6\n" +
                        "forward 3\n" +
                        "forward 7\n" +
                        "up 8\n" +
                        "down 6\n" +
                        "forward 2\n" +
                        "down 3\n" +
                        "forward 5\n" +
                        "down 3\n" +
                        "forward 6\n" +
                        "up 4\n" +
                        "forward 1\n" +
                        "forward 9\n" +
                        "up 9\n" +
                        "forward 3\n" +
                        "forward 5\n" +
                        "down 2\n" +
                        "down 4\n" +
                        "forward 4\n" +
                        "forward 8\n" +
                        "down 4\n" +
                        "forward 2\n" +
                        "forward 1\n" +
                        "forward 9\n" +
                        "forward 6\n" +
                        "forward 1\n" +
                        "down 7\n" +
                        "up 4\n" +
                        "down 8\n" +
                        "forward 3\n" +
                        "down 4\n" +
                        "forward 1\n" +
                        "forward 1\n" +
                        "up 7\n" +
                        "up 7\n" +
                        "down 1\n" +
                        "forward 5\n" +
                        "down 1\n" +
                        "forward 1\n" +
                        "forward 2\n" +
                        "forward 7\n" +
                        "forward 2\n" +
                        "down 7\n" +
                        "up 9\n" +
                        "up 2\n" +
                        "forward 2\n" +
                        "forward 8\n" +
                        "down 7\n" +
                        "down 6\n" +
                        "down 8\n" +
                        "up 8\n" +
                        "down 9\n" +
                        "up 5\n" +
                        "forward 3\n" +
                        "down 6\n" +
                        "forward 7\n" +
                        "up 7\n" +
                        "down 1\n" +
                        "forward 6\n" +
                        "forward 2\n" +
                        "forward 6\n" +
                        "forward 6\n" +
                        "down 7\n" +
                        "down 2\n" +
                        "up 7\n" +
                        "down 6\n" +
                        "down 8\n" +
                        "up 2\n" +
                        "down 9\n" +
                        "up 6\n" +
                        "up 8\n" +
                        "up 1\n" +
                        "forward 2\n" +
                        "down 5\n" +
                        "down 3\n" +
                        "down 2\n" +
                        "down 3\n" +
                        "forward 9\n" +
                        "forward 4\n" +
                        "down 1\n" +
                        "down 1\n" +
                        "up 4\n" +
                        "down 7\n" +
                        "up 1\n" +
                        "down 9\n" +
                        "up 6\n" +
                        "down 2\n" +
                        "down 6\n" +
                        "forward 3\n" +
                        "down 8\n" +
                        "down 5\n" +
                        "down 6\n" +
                        "down 2\n" +
                        "down 4\n" +
                        "forward 2\n" +
                        "forward 2\n" +
                        "down 9\n" +
                        "up 5\n" +
                        "forward 7\n" +
                        "up 8\n" +
                        "down 8\n" +
                        "down 5\n" +
                        "down 3\n" +
                        "down 1\n" +
                        "forward 9\n" +
                        "forward 1\n" +
                        "up 1\n" +
                        "down 8\n" +
                        "forward 8\n" +
                        "down 5\n" +
                        "forward 5\n" +
                        "down 2\n" +
                        "forward 2\n" +
                        "forward 1\n" +
                        "forward 1\n" +
                        "forward 7\n" +
                        "forward 8\n" +
                        "forward 9\n" +
                        "forward 2\n" +
                        "down 7\n" +
                        "forward 4\n" +
                        "forward 8\n" +
                        "forward 7\n" +
                        "up 9\n" +
                        "down 5\n" +
                        "down 6\n" +
                        "down 4\n" +
                        "up 9\n" +
                        "up 8\n" +
                        "down 1\n" +
                        "forward 3\n" +
                        "down 6\n" +
                        "down 8\n" +
                        "forward 1\n" +
                        "forward 9\n" +
                        "down 5\n" +
                        "down 9\n" +
                        "down 5\n" +
                        "forward 5\n" +
                        "forward 3\n" +
                        "forward 9\n" +
                        "down 2\n" +
                        "down 4\n" +
                        "forward 9\n" +
                        "forward 4\n" +
                        "down 5\n" +
                        "forward 9\n" +
                        "down 5\n" +
                        "up 2\n" +
                        "down 5\n" +
                        "forward 8\n" +
                        "down 9\n" +
                        "up 6\n" +
                        "down 6\n" +
                        "up 5\n" +
                        "down 1\n" +
                        "down 9\n" +
                        "down 4\n" +
                        "down 7\n" +
                        "down 3\n" +
                        "up 4\n" +
                        "forward 4\n" +
                        "forward 3\n" +
                        "down 4\n" +
                        "forward 9\n" +
                        "forward 4\n" +
                        "up 1\n" +
                        "forward 8\n" +
                        "up 8\n" +
                        "down 1\n" +
                        "forward 3\n" +
                        "forward 4\n" +
                        "forward 3\n" +
                        "forward 4\n" +
                        "forward 6\n" +
                        "down 6\n" +
                        "forward 3\n" +
                        "down 4\n" +
                        "forward 2\n" +
                        "down 5\n" +
                        "down 4\n" +
                        "forward 8\n" +
                        "up 8\n" +
                        "down 6\n" +
                        "down 7\n" +
                        "forward 6\n" +
                        "forward 3\n" +
                        "down 6\n" +
                        "down 1\n" +
                        "up 7\n" +
                        "down 8\n" +
                        "down 7\n" +
                        "down 6\n" +
                        "down 5\n" +
                        "down 1\n" +
                        "down 7\n" +
                        "up 9\n" +
                        "forward 5\n" +
                        "forward 8\n" +
                        "down 6\n" +
                        "down 1\n" +
                        "down 4\n" +
                        "down 5\n" +
                        "forward 5\n" +
                        "down 5\n" +
                        "down 1\n" +
                        "down 7\n" +
                        "up 1\n" +
                        "down 1\n" +
                        "forward 8\n" +
                        "forward 3\n" +
                        "down 9\n" +
                        "up 7\n" +
                        "down 4\n" +
                        "down 5\n" +
                        "forward 5\n" +
                        "forward 8\n" +
                        "forward 2\n" +
                        "down 6\n" +
                        "down 1\n" +
                        "up 5\n" +
                        "forward 3\n" +
                        "down 9\n" +
                        "forward 7\n" +
                        "forward 6\n" +
                        "down 6\n" +
                        "forward 7\n" +
                        "down 6\n" +
                        "down 5\n" +
                        "down 2\n" +
                        "up 5\n" +
                        "down 3\n" +
                        "forward 4\n" +
                        "forward 2\n" +
                        "down 4\n" +
                        "down 9\n" +
                        "down 4\n" +
                        "forward 2\n" +
                        "forward 7\n" +
                        "forward 8\n" +
                        "down 8\n" +
                        "forward 4\n" +
                        "forward 5\n" +
                        "down 9\n" +
                        "forward 7\n" +
                        "down 3\n" +
                        "down 9\n" +
                        "down 9\n" +
                        "up 7\n" +
                        "down 8\n" +
                        "up 9\n" +
                        "forward 2\n" +
                        "up 4\n" +
                        "forward 5\n" +
                        "down 4\n" +
                        "up 2\n" +
                        "up 9\n" +
                        "forward 4\n" +
                        "forward 7\n" +
                        "down 8\n" +
                        "up 2\n" +
                        "forward 5\n" +
                        "down 1\n" +
                        "down 2\n" +
                        "forward 8\n" +
                        "down 4\n" +
                        "forward 2\n" +
                        "forward 5\n" +
                        "forward 3\n" +
                        "down 7\n" +
                        "forward 6\n" +
                        "up 8\n" +
                        "down 2\n" +
                        "forward 2\n" +
                        "down 8\n" +
                        "forward 7\n" +
                        "up 7\n" +
                        "down 9\n" +
                        "forward 4\n" +
                        "up 8\n" +
                        "down 8\n" +
                        "forward 3\n" +
                        "forward 2\n" +
                        "up 8\n" +
                        "forward 8\n" +
                        "down 8\n" +
                        "down 8\n" +
                        "forward 4\n" +
                        "down 6\n" +
                        "down 6\n" +
                        "forward 7\n" +
                        "forward 2\n" +
                        "forward 1\n" +
                        "up 3\n" +
                        "forward 7\n" +
                        "up 4\n" +
                        "up 5\n" +
                        "down 7\n" +
                        "down 1\n" +
                        "forward 5\n" +
                        "down 2\n" +
                        "down 3\n" +
                        "down 1\n" +
                        "down 5\n" +
                        "forward 6\n" +
                        "down 7\n" +
                        "forward 6\n" +
                        "up 4\n" +
                        "down 7\n" +
                        "forward 6\n" +
                        "up 7\n" +
                        "up 5\n" +
                        "up 3\n" +
                        "forward 5\n" +
                        "forward 4\n" +
                        "forward 6\n" +
                        "forward 8\n" +
                        "up 5\n" +
                        "forward 7\n" +
                        "down 5\n" +
                        "forward 6\n" +
                        "down 8\n" +
                        "down 3\n" +
                        "down 4\n" +
                        "forward 6\n" +
                        "up 7\n" +
                        "down 2\n" +
                        "forward 8\n" +
                        "forward 5\n" +
                        "forward 1\n" +
                        "down 2\n" +
                        "down 6\n" +
                        "down 9\n" +
                        "up 7\n" +
                        "up 7\n" +
                        "forward 6\n" +
                        "forward 6\n" +
                        "up 3\n" +
                        "down 5\n" +
                        "forward 7\n" +
                        "forward 7\n" +
                        "down 5\n" +
                        "forward 3\n" +
                        "up 6\n" +
                        "forward 6\n" +
                        "forward 1\n" +
                        "down 8\n" +
                        "forward 8\n" +
                        "down 8\n" +
                        "up 8\n" +
                        "forward 3\n" +
                        "down 4\n" +
                        "up 7\n" +
                        "forward 2\n" +
                        "down 5\n" +
                        "forward 2\n" +
                        "up 3\n" +
                        "forward 2\n" +
                        "forward 1\n" +
                        "up 4\n" +
                        "up 5\n" +
                        "forward 5\n" +
                        "down 9\n" +
                        "forward 9\n" +
                        "up 1\n" +
                        "up 1\n" +
                        "down 5\n" +
                        "down 7\n" +
                        "forward 6\n" +
                        "forward 1\n" +
                        "up 2\n" +
                        "down 9\n" +
                        "down 7\n" +
                        "down 5\n" +
                        "forward 6\n" +
                        "up 7\n" +
                        "down 4\n" +
                        "forward 6\n" +
                        "forward 7\n" +
                        "forward 2\n" +
                        "down 6\n" +
                        "down 8\n" +
                        "forward 5\n" +
                        "forward 7\n" +
                        "down 9\n" +
                        "down 8\n" +
                        "up 9\n" +
                        "forward 7\n" +
                        "down 3\n" +
                        "down 6\n" +
                        "down 1\n" +
                        "down 9\n" +
                        "down 3\n" +
                        "forward 6\n" +
                        "down 3\n" +
                        "down 2\n" +
                        "up 5\n" +
                        "forward 6\n" +
                        "forward 9\n" +
                        "forward 5\n" +
                        "down 4\n" +
                        "forward 1\n" +
                        "forward 4\n" +
                        "up 2\n" +
                        "forward 3\n" +
                        "up 1\n" +
                        "down 4\n" +
                        "forward 8\n" +
                        "forward 2\n" +
                        "forward 1\n" +
                        "down 1\n" +
                        "forward 7\n" +
                        "down 2\n" +
                        "forward 1\n" +
                        "forward 2\n" +
                        "forward 8\n" +
                        "forward 5\n" +
                        "down 2\n" +
                        "up 6\n" +
                        "up 5\n" +
                        "up 9\n" +
                        "down 6\n" +
                        "forward 8\n" +
                        "up 6\n" +
                        "forward 9\n" +
                        "forward 2\n" +
                        "down 7\n" +
                        "down 8\n" +
                        "up 4\n" +
                        "down 1\n" +
                        "up 5\n" +
                        "up 5\n" +
                        "forward 7\n" +
                        "down 7\n" +
                        "forward 3\n" +
                        "down 7\n" +
                        "down 1\n" +
                        "forward 6\n" +
                        "forward 7\n" +
                        "down 2\n" +
                        "forward 4\n" +
                        "down 5\n" +
                        "forward 1\n" +
                        "down 6\n" +
                        "down 4\n" +
                        "forward 4\n" +
                        "up 2\n" +
                        "down 8\n" +
                        "up 2\n" +
                        "up 2\n" +
                        "forward 1\n" +
                        "down 3\n" +
                        "forward 1\n" +
                        "forward 4\n" +
                        "up 4\n" +
                        "up 4\n" +
                        "down 7\n" +
                        "down 2\n" +
                        "forward 2\n" +
                        "forward 1\n" +
                        "up 2\n" +
                        "forward 2\n" +
                        "forward 8\n" +
                        "down 1\n" +
                        "down 8\n" +
                        "forward 3\n" +
                        "down 6\n" +
                        "up 1\n" +
                        "forward 7\n" +
                        "forward 8\n" +
                        "forward 4\n" +
                        "down 5\n" +
                        "down 6\n" +
                        "down 3\n" +
                        "down 6\n" +
                        "down 4\n" +
                        "forward 8\n" +
                        "up 4\n" +
                        "up 4\n" +
                        "down 1\n" +
                        "down 8\n" +
                        "down 3\n" +
                        "down 6\n" +
                        "forward 2\n" +
                        "down 6\n" +
                        "forward 3\n" +
                        "up 1\n" +
                        "forward 9\n" +
                        "up 6\n" +
                        "up 6\n" +
                        "forward 9\n" +
                        "forward 5\n" +
                        "up 8\n" +
                        "down 2\n" +
                        "down 9\n" +
                        "forward 4\n" +
                        "down 5\n" +
                        "forward 8\n" +
                        "down 5\n" +
                        "up 6\n" +
                        "forward 1\n" +
                        "down 6\n" +
                        "up 9\n" +
                        "down 3\n" +
                        "forward 7\n" +
                        "down 4\n" +
                        "down 3\n" +
                        "down 7\n" +
                        "down 6\n" +
                        "forward 1\n" +
                        "forward 8\n" +
                        "forward 2\n" +
                        "forward 2\n" +
                        "forward 5\n" +
                        "forward 5\n" +
                        "forward 7\n" +
                        "forward 2\n" +
                        "down 2\n" +
                        "forward 2\n" +
                        "up 9\n" +
                        "down 8\n" +
                        "down 3\n" +
                        "forward 2\n" +
                        "forward 1\n" +
                        "down 4\n" +
                        "down 9\n" +
                        "forward 5\n" +
                        "forward 4\n" +
                        "forward 5\n" +
                        "down 1\n" +
                        "up 4\n" +
                        "down 2\n" +
                        "up 7\n" +
                        "down 1\n" +
                        "down 5\n" +
                        "forward 5\n" +
                        "up 6\n" +
                        "down 6\n" +
                        "forward 8\n" +
                        "down 3\n" +
                        "up 8\n" +
                        "up 2\n" +
                        "down 9\n" +
                        "forward 2\n" +
                        "down 8\n" +
                        "forward 4\n" +
                        "forward 3\n" +
                        "forward 8\n" +
                        "down 6\n" +
                        "forward 2\n" +
                        "down 5\n" +
                        "forward 7\n" +
                        "down 4\n" +
                        "down 2\n" +
                        "down 7\n" +
                        "up 2\n" +
                        "forward 8\n" +
                        "up 8\n" +
                        "down 2\n" +
                        "forward 9\n" +
                        "down 4\n" +
                        "down 8\n" +
                        "down 8\n" +
                        "down 6\n" +
                        "forward 6\n" +
                        "down 3\n" +
                        "forward 1\n" +
                        "forward 5\n" +
                        "down 3\n" +
                        "down 3\n" +
                        "up 8\n" +
                        "down 1\n" +
                        "down 1\n" +
                        "forward 1\n" +
                        "up 4\n" +
                        "forward 9\n" +
                        "forward 1\n" +
                        "up 4\n" +
                        "up 2\n" +
                        "forward 4\n" +
                        "forward 1\n" +
                        "forward 6\n" +
                        "forward 1\n" +
                        "forward 1\n" +
                        "forward 6\n" +
                        "up 9\n" +
                        "forward 9\n" +
                        "up 4\n" +
                        "forward 2\n" +
                        "forward 9\n" +
                        "forward 2\n" +
                        "forward 4\n" +
                        "forward 9\n" +
                        "down 6\n" +
                        "forward 5\n" +
                        "forward 9\n" +
                        "down 6\n" +
                        "down 8\n" +
                        "forward 5\n" +
                        "down 4\n" +
                        "forward 6\n" +
                        "forward 4\n" +
                        "down 4\n" +
                        "down 1\n" +
                        "forward 8\n" +
                        "up 7\n" +
                        "down 1\n" +
                        "down 2\n" +
                        "up 7\n" +
                        "forward 6\n" +
                        "down 5\n" +
                        "up 6\n" +
                        "down 7\n" +
                        "down 8\n" +
                        "down 2\n" +
                        "up 5\n" +
                        "forward 1\n" +
                        "up 5\n" +
                        "down 1\n" +
                        "down 6\n" +
                        "down 2\n" +
                        "down 3\n" +
                        "forward 8\n" +
                        "down 5\n" +
                        "forward 6", 0)
        );
    }

    @ParameterizedTest
    @MethodSource
    void task2(String input, int expectedResult) {
        Day2 testObject = new Day2(input);
        int result = testObject.task2();

        assertEquals(expectedResult, result);
    }

    static Stream<Arguments> task2() {
        return Stream.of(
                Arguments.of("forward 5\n" +
                        "down 5\n" +
                        "forward 8\n" +
                        "up 3\n" +
                        "down 8\n" +
                        "forward 2", 900),
                Arguments.of("forward 9\n" +
                        "down 8\n" +
                        "down 2\n" +
                        "down 4\n" +
                        "up 8\n" +
                        "forward 8\n" +
                        "down 7\n" +
                        "forward 3\n" +
                        "down 8\n" +
                        "down 9\n" +
                        "forward 7\n" +
                        "down 3\n" +
                        "forward 2\n" +
                        "down 6\n" +
                        "forward 8\n" +
                        "down 3\n" +
                        "down 4\n" +
                        "up 2\n" +
                        "forward 1\n" +
                        "up 7\n" +
                        "forward 7\n" +
                        "forward 4\n" +
                        "forward 4\n" +
                        "down 7\n" +
                        "forward 2\n" +
                        "forward 7\n" +
                        "forward 4\n" +
                        "up 5\n" +
                        "forward 4\n" +
                        "forward 8\n" +
                        "forward 8\n" +
                        "down 5\n" +
                        "forward 2\n" +
                        "forward 8\n" +
                        "forward 8\n" +
                        "up 1\n" +
                        "down 4\n" +
                        "down 3\n" +
                        "down 1\n" +
                        "up 9\n" +
                        "down 3\n" +
                        "forward 9\n" +
                        "down 4\n" +
                        "up 8\n" +
                        "up 3\n" +
                        "down 5\n" +
                        "forward 4\n" +
                        "down 4\n" +
                        "down 6\n" +
                        "down 8\n" +
                        "forward 2\n" +
                        "down 7\n" +
                        "forward 9\n" +
                        "up 7\n" +
                        "down 3\n" +
                        "forward 3\n" +
                        "forward 2\n" +
                        "down 4\n" +
                        "down 4\n" +
                        "forward 2\n" +
                        "forward 5\n" +
                        "forward 9\n" +
                        "down 9\n" +
                        "down 2\n" +
                        "forward 1\n" +
                        "up 4\n" +
                        "forward 9\n" +
                        "forward 9\n" +
                        "up 4\n" +
                        "down 2\n" +
                        "up 1\n" +
                        "up 7\n" +
                        "forward 7\n" +
                        "forward 6\n" +
                        "forward 1\n" +
                        "forward 8\n" +
                        "forward 2\n" +
                        "forward 4\n" +
                        "up 4\n" +
                        "down 5\n" +
                        "up 8\n" +
                        "down 4\n" +
                        "forward 4\n" +
                        "forward 2\n" +
                        "forward 2\n" +
                        "down 4\n" +
                        "up 3\n" +
                        "down 7\n" +
                        "down 5\n" +
                        "forward 7\n" +
                        "forward 9\n" +
                        "down 8\n" +
                        "up 1\n" +
                        "forward 5\n" +
                        "up 9\n" +
                        "down 1\n" +
                        "up 5\n" +
                        "down 4\n" +
                        "down 2\n" +
                        "down 5\n" +
                        "down 7\n" +
                        "down 3\n" +
                        "down 9\n" +
                        "forward 8\n" +
                        "up 3\n" +
                        "forward 4\n" +
                        "down 6\n" +
                        "down 4\n" +
                        "up 5\n" +
                        "down 3\n" +
                        "up 4\n" +
                        "forward 8\n" +
                        "forward 2\n" +
                        "down 1\n" +
                        "down 6\n" +
                        "down 9\n" +
                        "down 8\n" +
                        "forward 2\n" +
                        "down 6\n" +
                        "down 2\n" +
                        "up 7\n" +
                        "down 6\n" +
                        "down 4\n" +
                        "up 2\n" +
                        "forward 7\n" +
                        "down 4\n" +
                        "forward 4\n" +
                        "up 8\n" +
                        "down 1\n" +
                        "down 6\n" +
                        "forward 6\n" +
                        "down 5\n" +
                        "down 7\n" +
                        "up 9\n" +
                        "forward 2\n" +
                        "up 1\n" +
                        "down 1\n" +
                        "up 8\n" +
                        "forward 6\n" +
                        "forward 7\n" +
                        "up 1\n" +
                        "down 5\n" +
                        "down 3\n" +
                        "up 9\n" +
                        "down 2\n" +
                        "forward 5\n" +
                        "forward 1\n" +
                        "up 6\n" +
                        "up 4\n" +
                        "forward 6\n" +
                        "down 8\n" +
                        "forward 7\n" +
                        "forward 9\n" +
                        "forward 2\n" +
                        "forward 3\n" +
                        "forward 9\n" +
                        "forward 4\n" +
                        "down 9\n" +
                        "down 4\n" +
                        "forward 9\n" +
                        "forward 4\n" +
                        "forward 9\n" +
                        "forward 2\n" +
                        "forward 1\n" +
                        "down 3\n" +
                        "forward 5\n" +
                        "forward 2\n" +
                        "forward 7\n" +
                        "down 7\n" +
                        "down 4\n" +
                        "up 7\n" +
                        "forward 3\n" +
                        "forward 8\n" +
                        "forward 4\n" +
                        "down 4\n" +
                        "forward 9\n" +
                        "forward 2\n" +
                        "forward 9\n" +
                        "down 5\n" +
                        "forward 2\n" +
                        "down 5\n" +
                        "forward 2\n" +
                        "down 8\n" +
                        "up 8\n" +
                        "down 7\n" +
                        "forward 2\n" +
                        "forward 5\n" +
                        "down 5\n" +
                        "forward 8\n" +
                        "up 9\n" +
                        "forward 7\n" +
                        "forward 5\n" +
                        "forward 3\n" +
                        "down 4\n" +
                        "down 2\n" +
                        "forward 4\n" +
                        "down 4\n" +
                        "forward 6\n" +
                        "down 4\n" +
                        "forward 6\n" +
                        "forward 2\n" +
                        "down 9\n" +
                        "forward 7\n" +
                        "down 5\n" +
                        "up 5\n" +
                        "down 9\n" +
                        "down 5\n" +
                        "down 3\n" +
                        "up 4\n" +
                        "down 6\n" +
                        "down 2\n" +
                        "forward 5\n" +
                        "down 4\n" +
                        "down 1\n" +
                        "down 1\n" +
                        "up 7\n" +
                        "forward 9\n" +
                        "forward 6\n" +
                        "down 2\n" +
                        "down 8\n" +
                        "up 7\n" +
                        "up 2\n" +
                        "forward 9\n" +
                        "down 8\n" +
                        "up 6\n" +
                        "down 8\n" +
                        "down 6\n" +
                        "down 2\n" +
                        "down 9\n" +
                        "forward 5\n" +
                        "down 1\n" +
                        "forward 6\n" +
                        "forward 2\n" +
                        "forward 4\n" +
                        "down 7\n" +
                        "down 4\n" +
                        "down 8\n" +
                        "forward 8\n" +
                        "up 5\n" +
                        "up 8\n" +
                        "up 2\n" +
                        "up 2\n" +
                        "up 2\n" +
                        "down 5\n" +
                        "forward 6\n" +
                        "down 8\n" +
                        "down 2\n" +
                        "up 5\n" +
                        "up 2\n" +
                        "forward 7\n" +
                        "forward 4\n" +
                        "up 9\n" +
                        "forward 7\n" +
                        "up 7\n" +
                        "down 9\n" +
                        "forward 8\n" +
                        "down 5\n" +
                        "forward 4\n" +
                        "down 6\n" +
                        "forward 5\n" +
                        "up 2\n" +
                        "down 9\n" +
                        "down 3\n" +
                        "down 2\n" +
                        "down 3\n" +
                        "forward 2\n" +
                        "forward 4\n" +
                        "forward 9\n" +
                        "up 6\n" +
                        "forward 8\n" +
                        "down 9\n" +
                        "forward 1\n" +
                        "forward 1\n" +
                        "forward 1\n" +
                        "forward 4\n" +
                        "forward 3\n" +
                        "up 5\n" +
                        "forward 2\n" +
                        "down 8\n" +
                        "forward 6\n" +
                        "down 3\n" +
                        "down 9\n" +
                        "up 6\n" +
                        "forward 7\n" +
                        "up 3\n" +
                        "down 1\n" +
                        "forward 1\n" +
                        "forward 1\n" +
                        "forward 2\n" +
                        "forward 5\n" +
                        "down 9\n" +
                        "forward 1\n" +
                        "forward 1\n" +
                        "down 2\n" +
                        "forward 2\n" +
                        "forward 4\n" +
                        "up 8\n" +
                        "down 7\n" +
                        "forward 1\n" +
                        "up 3\n" +
                        "forward 7\n" +
                        "down 6\n" +
                        "forward 5\n" +
                        "up 4\n" +
                        "up 5\n" +
                        "forward 4\n" +
                        "down 7\n" +
                        "down 7\n" +
                        "down 9\n" +
                        "down 3\n" +
                        "down 1\n" +
                        "down 1\n" +
                        "down 9\n" +
                        "down 7\n" +
                        "forward 4\n" +
                        "up 3\n" +
                        "down 8\n" +
                        "down 3\n" +
                        "forward 7\n" +
                        "down 1\n" +
                        "down 8\n" +
                        "forward 5\n" +
                        "down 5\n" +
                        "down 1\n" +
                        "forward 5\n" +
                        "forward 6\n" +
                        "down 3\n" +
                        "down 8\n" +
                        "down 1\n" +
                        "forward 4\n" +
                        "up 5\n" +
                        "forward 5\n" +
                        "down 2\n" +
                        "down 2\n" +
                        "forward 5\n" +
                        "down 5\n" +
                        "forward 5\n" +
                        "forward 1\n" +
                        "down 2\n" +
                        "down 3\n" +
                        "down 3\n" +
                        "down 9\n" +
                        "down 6\n" +
                        "forward 6\n" +
                        "forward 9\n" +
                        "forward 9\n" +
                        "forward 6\n" +
                        "up 2\n" +
                        "up 4\n" +
                        "forward 7\n" +
                        "up 4\n" +
                        "down 4\n" +
                        "forward 4\n" +
                        "down 4\n" +
                        "up 2\n" +
                        "forward 5\n" +
                        "up 9\n" +
                        "down 8\n" +
                        "down 8\n" +
                        "down 1\n" +
                        "down 9\n" +
                        "forward 9\n" +
                        "down 4\n" +
                        "up 2\n" +
                        "up 3\n" +
                        "down 2\n" +
                        "forward 6\n" +
                        "up 4\n" +
                        "up 7\n" +
                        "down 3\n" +
                        "up 2\n" +
                        "forward 6\n" +
                        "down 7\n" +
                        "down 3\n" +
                        "down 6\n" +
                        "down 6\n" +
                        "forward 3\n" +
                        "forward 7\n" +
                        "up 8\n" +
                        "down 6\n" +
                        "forward 2\n" +
                        "down 3\n" +
                        "forward 5\n" +
                        "down 3\n" +
                        "forward 6\n" +
                        "up 4\n" +
                        "forward 1\n" +
                        "forward 9\n" +
                        "up 9\n" +
                        "forward 3\n" +
                        "forward 5\n" +
                        "down 2\n" +
                        "down 4\n" +
                        "forward 4\n" +
                        "forward 8\n" +
                        "down 4\n" +
                        "forward 2\n" +
                        "forward 1\n" +
                        "forward 9\n" +
                        "forward 6\n" +
                        "forward 1\n" +
                        "down 7\n" +
                        "up 4\n" +
                        "down 8\n" +
                        "forward 3\n" +
                        "down 4\n" +
                        "forward 1\n" +
                        "forward 1\n" +
                        "up 7\n" +
                        "up 7\n" +
                        "down 1\n" +
                        "forward 5\n" +
                        "down 1\n" +
                        "forward 1\n" +
                        "forward 2\n" +
                        "forward 7\n" +
                        "forward 2\n" +
                        "down 7\n" +
                        "up 9\n" +
                        "up 2\n" +
                        "forward 2\n" +
                        "forward 8\n" +
                        "down 7\n" +
                        "down 6\n" +
                        "down 8\n" +
                        "up 8\n" +
                        "down 9\n" +
                        "up 5\n" +
                        "forward 3\n" +
                        "down 6\n" +
                        "forward 7\n" +
                        "up 7\n" +
                        "down 1\n" +
                        "forward 6\n" +
                        "forward 2\n" +
                        "forward 6\n" +
                        "forward 6\n" +
                        "down 7\n" +
                        "down 2\n" +
                        "up 7\n" +
                        "down 6\n" +
                        "down 8\n" +
                        "up 2\n" +
                        "down 9\n" +
                        "up 6\n" +
                        "up 8\n" +
                        "up 1\n" +
                        "forward 2\n" +
                        "down 5\n" +
                        "down 3\n" +
                        "down 2\n" +
                        "down 3\n" +
                        "forward 9\n" +
                        "forward 4\n" +
                        "down 1\n" +
                        "down 1\n" +
                        "up 4\n" +
                        "down 7\n" +
                        "up 1\n" +
                        "down 9\n" +
                        "up 6\n" +
                        "down 2\n" +
                        "down 6\n" +
                        "forward 3\n" +
                        "down 8\n" +
                        "down 5\n" +
                        "down 6\n" +
                        "down 2\n" +
                        "down 4\n" +
                        "forward 2\n" +
                        "forward 2\n" +
                        "down 9\n" +
                        "up 5\n" +
                        "forward 7\n" +
                        "up 8\n" +
                        "down 8\n" +
                        "down 5\n" +
                        "down 3\n" +
                        "down 1\n" +
                        "forward 9\n" +
                        "forward 1\n" +
                        "up 1\n" +
                        "down 8\n" +
                        "forward 8\n" +
                        "down 5\n" +
                        "forward 5\n" +
                        "down 2\n" +
                        "forward 2\n" +
                        "forward 1\n" +
                        "forward 1\n" +
                        "forward 7\n" +
                        "forward 8\n" +
                        "forward 9\n" +
                        "forward 2\n" +
                        "down 7\n" +
                        "forward 4\n" +
                        "forward 8\n" +
                        "forward 7\n" +
                        "up 9\n" +
                        "down 5\n" +
                        "down 6\n" +
                        "down 4\n" +
                        "up 9\n" +
                        "up 8\n" +
                        "down 1\n" +
                        "forward 3\n" +
                        "down 6\n" +
                        "down 8\n" +
                        "forward 1\n" +
                        "forward 9\n" +
                        "down 5\n" +
                        "down 9\n" +
                        "down 5\n" +
                        "forward 5\n" +
                        "forward 3\n" +
                        "forward 9\n" +
                        "down 2\n" +
                        "down 4\n" +
                        "forward 9\n" +
                        "forward 4\n" +
                        "down 5\n" +
                        "forward 9\n" +
                        "down 5\n" +
                        "up 2\n" +
                        "down 5\n" +
                        "forward 8\n" +
                        "down 9\n" +
                        "up 6\n" +
                        "down 6\n" +
                        "up 5\n" +
                        "down 1\n" +
                        "down 9\n" +
                        "down 4\n" +
                        "down 7\n" +
                        "down 3\n" +
                        "up 4\n" +
                        "forward 4\n" +
                        "forward 3\n" +
                        "down 4\n" +
                        "forward 9\n" +
                        "forward 4\n" +
                        "up 1\n" +
                        "forward 8\n" +
                        "up 8\n" +
                        "down 1\n" +
                        "forward 3\n" +
                        "forward 4\n" +
                        "forward 3\n" +
                        "forward 4\n" +
                        "forward 6\n" +
                        "down 6\n" +
                        "forward 3\n" +
                        "down 4\n" +
                        "forward 2\n" +
                        "down 5\n" +
                        "down 4\n" +
                        "forward 8\n" +
                        "up 8\n" +
                        "down 6\n" +
                        "down 7\n" +
                        "forward 6\n" +
                        "forward 3\n" +
                        "down 6\n" +
                        "down 1\n" +
                        "up 7\n" +
                        "down 8\n" +
                        "down 7\n" +
                        "down 6\n" +
                        "down 5\n" +
                        "down 1\n" +
                        "down 7\n" +
                        "up 9\n" +
                        "forward 5\n" +
                        "forward 8\n" +
                        "down 6\n" +
                        "down 1\n" +
                        "down 4\n" +
                        "down 5\n" +
                        "forward 5\n" +
                        "down 5\n" +
                        "down 1\n" +
                        "down 7\n" +
                        "up 1\n" +
                        "down 1\n" +
                        "forward 8\n" +
                        "forward 3\n" +
                        "down 9\n" +
                        "up 7\n" +
                        "down 4\n" +
                        "down 5\n" +
                        "forward 5\n" +
                        "forward 8\n" +
                        "forward 2\n" +
                        "down 6\n" +
                        "down 1\n" +
                        "up 5\n" +
                        "forward 3\n" +
                        "down 9\n" +
                        "forward 7\n" +
                        "forward 6\n" +
                        "down 6\n" +
                        "forward 7\n" +
                        "down 6\n" +
                        "down 5\n" +
                        "down 2\n" +
                        "up 5\n" +
                        "down 3\n" +
                        "forward 4\n" +
                        "forward 2\n" +
                        "down 4\n" +
                        "down 9\n" +
                        "down 4\n" +
                        "forward 2\n" +
                        "forward 7\n" +
                        "forward 8\n" +
                        "down 8\n" +
                        "forward 4\n" +
                        "forward 5\n" +
                        "down 9\n" +
                        "forward 7\n" +
                        "down 3\n" +
                        "down 9\n" +
                        "down 9\n" +
                        "up 7\n" +
                        "down 8\n" +
                        "up 9\n" +
                        "forward 2\n" +
                        "up 4\n" +
                        "forward 5\n" +
                        "down 4\n" +
                        "up 2\n" +
                        "up 9\n" +
                        "forward 4\n" +
                        "forward 7\n" +
                        "down 8\n" +
                        "up 2\n" +
                        "forward 5\n" +
                        "down 1\n" +
                        "down 2\n" +
                        "forward 8\n" +
                        "down 4\n" +
                        "forward 2\n" +
                        "forward 5\n" +
                        "forward 3\n" +
                        "down 7\n" +
                        "forward 6\n" +
                        "up 8\n" +
                        "down 2\n" +
                        "forward 2\n" +
                        "down 8\n" +
                        "forward 7\n" +
                        "up 7\n" +
                        "down 9\n" +
                        "forward 4\n" +
                        "up 8\n" +
                        "down 8\n" +
                        "forward 3\n" +
                        "forward 2\n" +
                        "up 8\n" +
                        "forward 8\n" +
                        "down 8\n" +
                        "down 8\n" +
                        "forward 4\n" +
                        "down 6\n" +
                        "down 6\n" +
                        "forward 7\n" +
                        "forward 2\n" +
                        "forward 1\n" +
                        "up 3\n" +
                        "forward 7\n" +
                        "up 4\n" +
                        "up 5\n" +
                        "down 7\n" +
                        "down 1\n" +
                        "forward 5\n" +
                        "down 2\n" +
                        "down 3\n" +
                        "down 1\n" +
                        "down 5\n" +
                        "forward 6\n" +
                        "down 7\n" +
                        "forward 6\n" +
                        "up 4\n" +
                        "down 7\n" +
                        "forward 6\n" +
                        "up 7\n" +
                        "up 5\n" +
                        "up 3\n" +
                        "forward 5\n" +
                        "forward 4\n" +
                        "forward 6\n" +
                        "forward 8\n" +
                        "up 5\n" +
                        "forward 7\n" +
                        "down 5\n" +
                        "forward 6\n" +
                        "down 8\n" +
                        "down 3\n" +
                        "down 4\n" +
                        "forward 6\n" +
                        "up 7\n" +
                        "down 2\n" +
                        "forward 8\n" +
                        "forward 5\n" +
                        "forward 1\n" +
                        "down 2\n" +
                        "down 6\n" +
                        "down 9\n" +
                        "up 7\n" +
                        "up 7\n" +
                        "forward 6\n" +
                        "forward 6\n" +
                        "up 3\n" +
                        "down 5\n" +
                        "forward 7\n" +
                        "forward 7\n" +
                        "down 5\n" +
                        "forward 3\n" +
                        "up 6\n" +
                        "forward 6\n" +
                        "forward 1\n" +
                        "down 8\n" +
                        "forward 8\n" +
                        "down 8\n" +
                        "up 8\n" +
                        "forward 3\n" +
                        "down 4\n" +
                        "up 7\n" +
                        "forward 2\n" +
                        "down 5\n" +
                        "forward 2\n" +
                        "up 3\n" +
                        "forward 2\n" +
                        "forward 1\n" +
                        "up 4\n" +
                        "up 5\n" +
                        "forward 5\n" +
                        "down 9\n" +
                        "forward 9\n" +
                        "up 1\n" +
                        "up 1\n" +
                        "down 5\n" +
                        "down 7\n" +
                        "forward 6\n" +
                        "forward 1\n" +
                        "up 2\n" +
                        "down 9\n" +
                        "down 7\n" +
                        "down 5\n" +
                        "forward 6\n" +
                        "up 7\n" +
                        "down 4\n" +
                        "forward 6\n" +
                        "forward 7\n" +
                        "forward 2\n" +
                        "down 6\n" +
                        "down 8\n" +
                        "forward 5\n" +
                        "forward 7\n" +
                        "down 9\n" +
                        "down 8\n" +
                        "up 9\n" +
                        "forward 7\n" +
                        "down 3\n" +
                        "down 6\n" +
                        "down 1\n" +
                        "down 9\n" +
                        "down 3\n" +
                        "forward 6\n" +
                        "down 3\n" +
                        "down 2\n" +
                        "up 5\n" +
                        "forward 6\n" +
                        "forward 9\n" +
                        "forward 5\n" +
                        "down 4\n" +
                        "forward 1\n" +
                        "forward 4\n" +
                        "up 2\n" +
                        "forward 3\n" +
                        "up 1\n" +
                        "down 4\n" +
                        "forward 8\n" +
                        "forward 2\n" +
                        "forward 1\n" +
                        "down 1\n" +
                        "forward 7\n" +
                        "down 2\n" +
                        "forward 1\n" +
                        "forward 2\n" +
                        "forward 8\n" +
                        "forward 5\n" +
                        "down 2\n" +
                        "up 6\n" +
                        "up 5\n" +
                        "up 9\n" +
                        "down 6\n" +
                        "forward 8\n" +
                        "up 6\n" +
                        "forward 9\n" +
                        "forward 2\n" +
                        "down 7\n" +
                        "down 8\n" +
                        "up 4\n" +
                        "down 1\n" +
                        "up 5\n" +
                        "up 5\n" +
                        "forward 7\n" +
                        "down 7\n" +
                        "forward 3\n" +
                        "down 7\n" +
                        "down 1\n" +
                        "forward 6\n" +
                        "forward 7\n" +
                        "down 2\n" +
                        "forward 4\n" +
                        "down 5\n" +
                        "forward 1\n" +
                        "down 6\n" +
                        "down 4\n" +
                        "forward 4\n" +
                        "up 2\n" +
                        "down 8\n" +
                        "up 2\n" +
                        "up 2\n" +
                        "forward 1\n" +
                        "down 3\n" +
                        "forward 1\n" +
                        "forward 4\n" +
                        "up 4\n" +
                        "up 4\n" +
                        "down 7\n" +
                        "down 2\n" +
                        "forward 2\n" +
                        "forward 1\n" +
                        "up 2\n" +
                        "forward 2\n" +
                        "forward 8\n" +
                        "down 1\n" +
                        "down 8\n" +
                        "forward 3\n" +
                        "down 6\n" +
                        "up 1\n" +
                        "forward 7\n" +
                        "forward 8\n" +
                        "forward 4\n" +
                        "down 5\n" +
                        "down 6\n" +
                        "down 3\n" +
                        "down 6\n" +
                        "down 4\n" +
                        "forward 8\n" +
                        "up 4\n" +
                        "up 4\n" +
                        "down 1\n" +
                        "down 8\n" +
                        "down 3\n" +
                        "down 6\n" +
                        "forward 2\n" +
                        "down 6\n" +
                        "forward 3\n" +
                        "up 1\n" +
                        "forward 9\n" +
                        "up 6\n" +
                        "up 6\n" +
                        "forward 9\n" +
                        "forward 5\n" +
                        "up 8\n" +
                        "down 2\n" +
                        "down 9\n" +
                        "forward 4\n" +
                        "down 5\n" +
                        "forward 8\n" +
                        "down 5\n" +
                        "up 6\n" +
                        "forward 1\n" +
                        "down 6\n" +
                        "up 9\n" +
                        "down 3\n" +
                        "forward 7\n" +
                        "down 4\n" +
                        "down 3\n" +
                        "down 7\n" +
                        "down 6\n" +
                        "forward 1\n" +
                        "forward 8\n" +
                        "forward 2\n" +
                        "forward 2\n" +
                        "forward 5\n" +
                        "forward 5\n" +
                        "forward 7\n" +
                        "forward 2\n" +
                        "down 2\n" +
                        "forward 2\n" +
                        "up 9\n" +
                        "down 8\n" +
                        "down 3\n" +
                        "forward 2\n" +
                        "forward 1\n" +
                        "down 4\n" +
                        "down 9\n" +
                        "forward 5\n" +
                        "forward 4\n" +
                        "forward 5\n" +
                        "down 1\n" +
                        "up 4\n" +
                        "down 2\n" +
                        "up 7\n" +
                        "down 1\n" +
                        "down 5\n" +
                        "forward 5\n" +
                        "up 6\n" +
                        "down 6\n" +
                        "forward 8\n" +
                        "down 3\n" +
                        "up 8\n" +
                        "up 2\n" +
                        "down 9\n" +
                        "forward 2\n" +
                        "down 8\n" +
                        "forward 4\n" +
                        "forward 3\n" +
                        "forward 8\n" +
                        "down 6\n" +
                        "forward 2\n" +
                        "down 5\n" +
                        "forward 7\n" +
                        "down 4\n" +
                        "down 2\n" +
                        "down 7\n" +
                        "up 2\n" +
                        "forward 8\n" +
                        "up 8\n" +
                        "down 2\n" +
                        "forward 9\n" +
                        "down 4\n" +
                        "down 8\n" +
                        "down 8\n" +
                        "down 6\n" +
                        "forward 6\n" +
                        "down 3\n" +
                        "forward 1\n" +
                        "forward 5\n" +
                        "down 3\n" +
                        "down 3\n" +
                        "up 8\n" +
                        "down 1\n" +
                        "down 1\n" +
                        "forward 1\n" +
                        "up 4\n" +
                        "forward 9\n" +
                        "forward 1\n" +
                        "up 4\n" +
                        "up 2\n" +
                        "forward 4\n" +
                        "forward 1\n" +
                        "forward 6\n" +
                        "forward 1\n" +
                        "forward 1\n" +
                        "forward 6\n" +
                        "up 9\n" +
                        "forward 9\n" +
                        "up 4\n" +
                        "forward 2\n" +
                        "forward 9\n" +
                        "forward 2\n" +
                        "forward 4\n" +
                        "forward 9\n" +
                        "down 6\n" +
                        "forward 5\n" +
                        "forward 9\n" +
                        "down 6\n" +
                        "down 8\n" +
                        "forward 5\n" +
                        "down 4\n" +
                        "forward 6\n" +
                        "forward 4\n" +
                        "down 4\n" +
                        "down 1\n" +
                        "forward 8\n" +
                        "up 7\n" +
                        "down 1\n" +
                        "down 2\n" +
                        "up 7\n" +
                        "forward 6\n" +
                        "down 5\n" +
                        "up 6\n" +
                        "down 7\n" +
                        "down 8\n" +
                        "down 2\n" +
                        "up 5\n" +
                        "forward 1\n" +
                        "up 5\n" +
                        "down 1\n" +
                        "down 6\n" +
                        "down 2\n" +
                        "down 3\n" +
                        "forward 8\n" +
                        "down 5\n" +
                        "forward 6", 0)
        );
    }
}