package AoC2022.Day2;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.*;

class Day2Test {

    @ParameterizedTest
    @MethodSource
    public void task1(String input, long expected){
        Day2 testObject = new Day2(input);
        long result = testObject.solveTask1();

        assertEquals(expected, result);
    }

    public static Stream<Arguments> task1(){
        return Stream.of(
                Arguments.of("A Y\n" +
                        "B X\n" +
                        "C Z", 15),
                Arguments.of("C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "B Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B Y\n" +
                        "A X\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "B X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "C X\n" +
                        "A X\n" +
                        "C X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "B Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A Y\n" +
                        "B X\n" +
                        "B Z\n" +
                        "C Z\n" +
                        "C Z\n" +
                        "A X\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Z\n" +
                        "C X\n" +
                        "A Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "B X\n" +
                        "A Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "B Z\n" +
                        "B Z\n" +
                        "B Z\n" +
                        "B X\n" +
                        "C X\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Z\n" +
                        "A Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Z\n" +
                        "B Z\n" +
                        "A Z\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "A X\n" +
                        "A Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C X\n" +
                        "B Y\n" +
                        "C Z\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Z\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B X\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "A Y\n" +
                        "A X\n" +
                        "B X\n" +
                        "B Z\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "A X\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "A Z\n" +
                        "B Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B X\n" +
                        "A X\n" +
                        "A X\n" +
                        "C X\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "A X\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Z\n" +
                        "B X\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Z\n" +
                        "B Z\n" +
                        "A X\n" +
                        "B X\n" +
                        "C X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "A Z\n" +
                        "B X\n" +
                        "B X\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B X\n" +
                        "A Z\n" +
                        "B X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "B Y\n" +
                        "B Z\n" +
                        "A X\n" +
                        "B X\n" +
                        "B Y\n" +
                        "C X\n" +
                        "A Y\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Z\n" +
                        "C X\n" +
                        "A Z\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Z\n" +
                        "C X\n" +
                        "C Z\n" +
                        "B X\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "B Z\n" +
                        "B X\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A Y\n" +
                        "B Z\n" +
                        "C X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "B Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A Y\n" +
                        "B Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C X\n" +
                        "B X\n" +
                        "C Z\n" +
                        "A X\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "B Y\n" +
                        "C Y\n" +
                        "A Y\n" +
                        "C X\n" +
                        "A X\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "A X\n" +
                        "C X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Z\n" +
                        "B Z\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C X\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Z\n" +
                        "C X\n" +
                        "A X\n" +
                        "A X\n" +
                        "B X\n" +
                        "A Z\n" +
                        "A X\n" +
                        "C X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "B Z\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C X\n" +
                        "A Z\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "B X\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B Z\n" +
                        "A X\n" +
                        "C X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "B X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "B Y\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Z\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C X\n" +
                        "B X\n" +
                        "A X\n" +
                        "A X\n" +
                        "B X\n" +
                        "A X\n" +
                        "C X\n" +
                        "A Z\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C X\n" +
                        "B Y\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "A Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A Z\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "B Z\n" +
                        "A Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "B X\n" +
                        "A Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C X\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "A Y\n" +
                        "C Z\n" +
                        "B X\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "A Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "A Y\n" +
                        "C X\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A Z\n" +
                        "A X\n" +
                        "C Z\n" +
                        "B X\n" +
                        "C X\n" +
                        "B X\n" +
                        "B Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "B X\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "B X\n" +
                        "A Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "B Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Z\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C X\n" +
                        "C Z\n" +
                        "C X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A Z\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "B Z\n" +
                        "B Z\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B Z\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "A Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "A X\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Z\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C X\n" +
                        "A Y\n" +
                        "A Z\n" +
                        "B Z\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "B X\n" +
                        "A X\n" +
                        "A Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "B Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C X\n" +
                        "A X\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Z\n" +
                        "B X\n" +
                        "C X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "B X\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Z\n" +
                        "C X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Z\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "B X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Z\n" +
                        "C Z\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "B Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "A X\n" +
                        "C X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B Z\n" +
                        "C Z\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A Y\n" +
                        "C Z\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "B Y\n" +
                        "C Y\n" +
                        "A Z\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "B X\n" +
                        "B Z\n" +
                        "A X\n" +
                        "B X\n" +
                        "A X\n" +
                        "C X\n" +
                        "A X\n" +
                        "B X\n" +
                        "A Y\n" +
                        "B Z\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "A Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A Z\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "B X\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Z\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A Z\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A Z\n" +
                        "B X\n" +
                        "C Z\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Z\n" +
                        "A X\n" +
                        "A Z\n" +
                        "C Z\n" +
                        "B Y\n" +
                        "B Z\n" +
                        "C Z\n" +
                        "C Z\n" +
                        "A X\n" +
                        "B X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A Z\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A Z\n" +
                        "C X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A Z\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "B X\n" +
                        "B Z\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "A Y\n" +
                        "A Z\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "A Y\n" +
                        "C Z\n" +
                        "C Z\n" +
                        "C X\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "A X\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "A Y\n" +
                        "A X\n" +
                        "B Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "B Z\n" +
                        "A X\n" +
                        "B X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "A X\n" +
                        "A Z\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C X\n" +
                        "A X\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C X\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Z\n" +
                        "A X\n" +
                        "A Z\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B Z\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "B Y\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A Z\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Z\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A Z\n" +
                        "B X\n" +
                        "A X\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "B Y\n" +
                        "B X\n" +
                        "C X\n" +
                        "C X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C X\n" +
                        "B Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "B Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A Z\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Z\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C X\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A Z\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "B X\n" +
                        "B Z\n" +
                        "A X\n" +
                        "C Z\n" +
                        "C X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C X\n" +
                        "B Z\n" +
                        "A Z\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Y\n" +
                        "C Z\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C X\n" +
                        "B X\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "B Z\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C X\n" +
                        "B Z\n" +
                        "A X\n" +
                        "A X\n" +
                        "C X\n" +
                        "C X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "A X\n" +
                        "C X\n" +
                        "C X\n" +
                        "C Z\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Z\n" +
                        "A Z\n" +
                        "B X\n" +
                        "C Z\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B Z\n" +
                        "B Z\n" +
                        "C Z\n" +
                        "A Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C X\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "A Y\n" +
                        "B X\n" +
                        "C Z\n" +
                        "B Z\n" +
                        "B Z\n" +
                        "C X\n" +
                        "B Z\n" +
                        "C X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C X\n" +
                        "C X\n" +
                        "B X\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Z\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B Z\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "B X\n" +
                        "B X\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "B X\n" +
                        "A Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Z\n" +
                        "A X\n" +
                        "B Z\n" +
                        "A Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Z\n" +
                        "B X\n" +
                        "B Z\n" +
                        "B X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C X\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "B X\n" +
                        "A X\n" +
                        "B X\n" +
                        "B Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Z\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "B X\n" +
                        "A Z\n" +
                        "C Z\n" +
                        "B Z\n" +
                        "A X\n" +
                        "A X\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Z\n" +
                        "B X\n" +
                        "A X\n" +
                        "A X\n" +
                        "B X\n" +
                        "B X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "A Z\n" +
                        "C X\n" +
                        "C Z\n" +
                        "B X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "A X\n" +
                        "A Z\n" +
                        "C X\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "B Z\n" +
                        "C Z\n" +
                        "C Z\n" +
                        "A X\n" +
                        "B X\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Z\n" +
                        "B Y\n" +
                        "A X\n" +
                        "C Z\n" +
                        "A Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "A Z\n" +
                        "A X\n" +
                        "A Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B Z\n" +
                        "B X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "B Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "A X\n" +
                        "C X\n" +
                        "C Y\n" +
                        "A Y\n" +
                        "A X\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "A X\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Z\n" +
                        "B X\n" +
                        "B X\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "B Z\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "A Y\n" +
                        "B Z\n" +
                        "B Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "B Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B X\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "B X\n" +
                        "B Z\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B Z\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C X\n" +
                        "A X\n" +
                        "C X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "B X\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "C X\n" +
                        "A X\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "B Z\n" +
                        "B Z\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "A X\n" +
                        "B X\n" +
                        "A Y\n" +
                        "B Z\n" +
                        "A X\n" +
                        "C Z\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "A Y\n" +
                        "B X\n" +
                        "B Z\n" +
                        "A Y\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A Z\n" +
                        "B Z\n" +
                        "B Z\n" +
                        "A X\n" +
                        "A Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Z\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "B Z\n" +
                        "C Z\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Z\n" +
                        "B X\n" +
                        "C Z\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C X\n" +
                        "A X\n" +
                        "A X\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "B Z\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A Z\n" +
                        "A X\n" +
                        "C Z\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "B Y\n" +
                        "A X\n" +
                        "B Z\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "B X\n" +
                        "B X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C X\n" +
                        "A X\n" +
                        "A X\n" +
                        "B Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B Z\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Z\n" +
                        "B X\n" +
                        "A X\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "B X\n" +
                        "A Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B Z\n" +
                        "B X\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "A X\n" +
                        "C Z\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A X\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A X\n" +
                        "B Z\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "B X\n" +
                        "C X\n" +
                        "C X\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A X\n" +
                        "C Y\n" +
                        "A Y\n" +
                        "B X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B X\n" +
                        "A X\n" +
                        "B Z\n" +
                        "C Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "B Y\n" +
                        "C Z\n" +
                        "C Y\n" +
                        "C X\n" +
                        "A X\n" +
                        "A Z\n" +
                        "C Y\n" +
                        "A X\n" +
                        "A Y\n" +
                        "B X\n" +
                        "C X\n" +
                        "B X\n" +
                        "B X\n" +
                        "B X\n" +
                        "C X\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "C Y\n" +
                        "A Z\n" +
                        "A X\n" +
                        "C Y\n" +
                        "C X\n" +
                        "A Y\n" +
                        "A X", 0)
        );
    }

}